(function(_ds){var window=this;'use strict';var o1=function(a){return(void 0===a?"":a).toLowerCase().trim().replace(/\s+/g,"-").replace(/[!@#\$%\^&\*\(\)\{\}<>\?\\\/'"]+/g,"").trim()},p1=function(){var a=_ds.R.call(this,["devsite-tabs"])||this;a.m=new _ds.Gl;a.o=!1;a.C=new _ds.Rl;a.j=null;return a},q1=function(a,b){var c=a.getBoundingClientRect();a.dispatchEvent(new CustomEvent("devsite-sticky-freeze",{bubbles:!0}));var d=a.getAttribute("scope");Array.from(a.ownerDocument.querySelectorAll('devsite-selector[scope="'+d+'"]:not([active="'+
(b+'"])'))).forEach(function(h){h!==a&&h.setAttribute("tab-to-select",b)});a.setAttribute("active",b);var e=a.getBoundingClientRect();window.scrollTo(_ds.xk(document).x,_ds.xk(document).y+e.top-c.top);a.hasAttribute("no-pref")||a.C.set("pref_ds_"+d,b);var g;Array.from(a.children).forEach(function(h){!g&&h.matches("devsite-tabs")&&(g=h.querySelector('[tab="'+b+'"]'))});g&&g.id&&_ds.nm("#"+g.id,!0);a.dispatchEvent(new CustomEvent("devsite-content-updated",{bubbles:!0}))},r1=function(a){a.j&&a.m.listen(a.j,
"click",function(b){if(!b.defaultPrevented){b.preventDefault();b.stopPropagation();document.body.dispatchEvent(new CustomEvent("devsite-close-overflow-tabs"));b=b.target;for(var c;!c&&b!==a;)"TAB"===b.tagName.toUpperCase()&&(c=b),b=b.parentNode;c&&q1(a,c.getAttribute("tab"))}})},s1=function(a){a.o=!0;var b=a.getAttribute("scope"),c=null,d=_ds.lm().searchParams.get("tab");d&&(c=o1(d));c||a.hasAttribute("no-pref")||(c=a.C.get("pref_ds_"+b));var e=a.ownerDocument.createElement("devsite-tabs");e.setAttribute("role",
"tablist");a.hasAttribute("no-overflow")&&e.setAttribute("no-overflow","");a.j=e;Array.from(a.children).filter(function(h){return h.matches("section")}).forEach(function(h){var k=a.ownerDocument.createElement("tab"),l=a.ownerDocument.createElement("a");h.querySelector(".two-line-tab")&&k.setAttribute("two-line","");k.setAttribute("role","tab");k.setAttribute("aria-selected","false");var m=h.querySelector("h1,h2,h3,h4,h5,h6"),p="";if(m&&""!==m.textContent.trim()){p="";if(m.id)var q=m.id;var t=m.querySelector(".firebase-platform-label");
t&&(p=t.textContent.trim(),_ds.Kk(t));t=m.textContent;var u=h.querySelector("[tab-label]");u&&(p=u.getAttribute("tab-label"));_ds.Kk(m);p?(u=a.ownerDocument.createElement("span"),u.setAttribute("tab-label",p),u.textContent=t.trim(),l.appendChild(u),p=o1(t+" "+p)):(l.append.apply(l,_ds.ya(m.childNodes)),p=o1(t)||"tab");k.setAttribute("aria-controls","tabpanel-"+p);l.id="aria-tab-"+p;l.setAttribute("role","button");m.hasAttributes()&&Array.from(m.attributes).forEach(function(v){v.name.startsWith("track-")&&
l.setAttribute(v.name,v.value)})}else p="\uc624\ub958",m&&(p=m.getAttribute("data-text")||"\uc624\ub958"),l.textContent=p,p=o1(p);_ds.Id(l,"#"+p);k.appendChild(l);e.querySelector('[tab="'+p+'"]')||(k.setAttribute("tab",p),q&&(k.id=q),e.appendChild(k));h.setAttribute("tab",p);h.setAttribute("role","tabpanel");h.setAttribute("aria-labelledby","aria-tab-"+p);h.setAttribute("tabindex","0");h.id="tabpanel-"+p});_ds.Jk(a,e,0);b=_ds.lm().hash.substring(1);var g=Array.from(a.children);d=e.querySelector('tab[id="'+
b+'"]');(g=g.find(function(h){return h.matches(".selected")}))&&g.classList.remove("selected");b&&d?a.setAttribute("active",d.getAttribute("tab")):c&&e.querySelector('[tab="'+c+'"]')?a.setAttribute("tab-to-select",c):g?a.setAttribute("active",g.getAttribute("tab")):a.hasAttribute("active")||a.setAttribute("active",e.querySelector("[tab]").getAttribute("tab"));a.setAttribute("ready","")},u1=function(a){Array.from(a.children).forEach(function(b){if(b.matches(".ds-selector-tabs,.ds-selector-dropdown,.code-sample,.data-sample")){var c=
b.getAttribute("data-ds-scope");c&&a.setAttribute("scope",c);var d=".ds-selector-tabs,.ds-selector-dropdown,.code-sample,.data-sample".split(/[,.]/).filter(function(e){return e.length});Array.from(b.classList).forEach(function(e){d.includes(e)||a.classList.add(e)});for(b.hasAttribute("no-overflow")&&a.setAttribute("no-overflow","");b.childNodes.length;)a.appendChild(b.childNodes[0]);_ds.Kk(b)}});Array.from(a.children).forEach(function(b){b.matches(".kd-tabbed-horz,.kd-tabbed-vert")&&t1(a,b)})},t1=
function(a,b){Array.from(b.children).forEach(function(c){if(c.matches("article")){var d=a.ownerDocument.createElement("section");for(c.classList.contains("selected")&&d.classList.add("selected");c.childNodes.length;)d.appendChild(c.childNodes[0]);var e=d.querySelector("header");if(e){var g=a.ownerDocument.createElement("h3");e.childNodes.length&&g.append.apply(g,_ds.ya(e.childNodes));g.id=e.id;_ds.Lk(g,e)}a.appendChild(d);_ds.Kk(c)}});_ds.Kk(b)};_ds.w(p1,_ds.R);
p1.prototype.connectedCallback=function(){u1(this);this.getAttribute("scope")||this.setAttribute("scope","auto");this.o||s1(this);r1(this)};p1.prototype.disconnectedCallback=function(){_ds.Ml(this.m)};
p1.prototype.attributeChangedCallback=function(a,b,c){var d=this,e=[],g=Array.from(this.children);g.forEach(function(k){k.matches('section[tab="'+c+'"]')?e.push(k):k.matches("devsite-tabs")&&(k=k.querySelector('tab[tab="'+c+'"]'))&&e.push(k)});"active"===a&&c&&(e.length?(g.forEach(function(k){if(k.matches("section[tab][active]"))k.removeAttribute("active");else if(k.matches("devsite-tabs")){var l=k.querySelector("tab[tab][active]");l&&(l.removeAttribute("active"),l.setAttribute("aria-selected","false"),
(k=k.querySelector("a[aria-selected=true]"))&&k.removeAttribute("aria-selected"))}}),e.forEach(function(k){k.setAttribute("active","");if(k.matches("tab")){k.setAttribute("aria-selected","true");var l=k.querySelector("a");l&&l.setAttribute("aria-selected","true")}Array.from(k.querySelectorAll("iframe[data-src]")).forEach(function(m){m.setAttribute("src",m.getAttribute("data-src"));m.removeAttribute("data-src")})})):this.setAttribute(a,b));if("tab-to-select"===a&&c){if(e.length)this.setAttribute("active",
c);else{var h=this.getAttribute("active");g.forEach(function(k){k.matches("devsite-tabs")&&(k=k.querySelector('tab[tab="'+h+'"]'))&&d.setAttribute("active",k.getAttribute("tab"))})}this.removeAttribute("tab-to-select")}};_ds.n.Object.defineProperties(p1,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["active","tab-to-select"]}}});p1.prototype.attributeChangedCallback=p1.prototype.attributeChangedCallback;p1.prototype.disconnectedCallback=p1.prototype.disconnectedCallback;
p1.prototype.connectedCallback=p1.prototype.connectedCallback;try{window.customElements.define("devsite-selector",p1)}catch(a){console.warn("devsite.app.customElement.DevsiteSelector",a)};})(_ds_www);
