(function(_ds){var window=this;'use strict';var z0=function(a){var b=arguments.length;if(1==b&&Array.isArray(arguments[0]))return z0.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c},A0=function(a,b,c,d,e,g,h,k,l,m){this.h=a;this.C=b;this.G=c;this.m=d;this.o=e;this.D=g;this.F=h;this.O=k;this.j=l;this.J=m},B0=function(a){return new A0(a.m,a.o,a.O,a.h,a.j,a.C,a.J,a.F,a.D,a.G)},C0=function(a,b){a.G=b;return a},D0=function(a,b){a.D=b;return a},E0=function(a,b){a.F=b;return a},F0=function(){this.m=null;
this.o="";this.G=this.D=this.F=this.J=this.C=this.j=this.h=this.O=null},G0=function(a){var b=a.ma;b=(b=b&&"composed"in b&&b&&"composedPath"in b&&b.composed&&b.composedPath())&&0<b.length?b[0]:a.target;return B0(C0(D0(E0((new F0).keyCode(a.keyCode||0).key(a.key||"").shiftKey(!!a.shiftKey).altKey(!!a.altKey).ctrlKey(!!a.ctrlKey).metaKey(!!a.metaKey).target(a.target),b),function(){return a.preventDefault()}),function(){return a.stopPropagation()}))},H0=function(a,b,c){_ds.dh.call(this,a,c);this.j=b},
I0=function(a){this.h=a||null;this.next=a?null:{}},J0=function(a,b){b.shift().forEach(function(c){var d=a[c];d&&(0==b.length?d.h&&delete a[c]:d.next&&(J0(d.next,b.slice(0)),_ds.ac(d.next)&&delete a[c]))})},M0=function(a){a=a.replace(/[ +]*\+[ +]*/g,"+").replace(/[ ]+/g," ").toLowerCase();a=a.split(" ");for(var b=[],c,d=0;c=a[d];d++){var e=c.split("+"),g=null,h=null;c=0;for(var k,l=0;k=e[l];l++){switch(k){case "shift":c|=1;continue;case "ctrl":c|=2;continue;case "alt":c|=4;continue;case "meta":c|=
8;continue}e=void 0;g=k;if(!K0){h={};for(e in L0)h[L0[e]]=_ds.QB(parseInt(e,10));K0=h}h=K0[g];g=k;break}b.push({key:g,keyCode:h,modifiers:c})}return b},N0=function(a,b,c){c=c||0;b=["c_"+b+"_"+c];""!=a&&b.push("n_"+a+"_"+c);return b},O0=function(a,b){if("string"===typeof b[a])a=M0(b[a]).map(function(e){return N0(e.key||"",e.keyCode,e.modifiers)});else{var c=b,d=a;Array.isArray(b[a])&&(c=b[a],d=0);for(a=[];d<c.length;d+=2)a.push(N0("",c[d],c[d+1]))}return a},P0=function(a,b){32==a.D&&32==b.h&&(0,b.j)();
a.D=null},Q0=function(a){return _ds.HJ&&a.o&&a.m},R0=function(a,b,c){var d=b.shift();d.forEach(function(e){if((e=a[e])&&(0==b.length||e.h))throw Error("Keyboard shortcut conflicts with existing shortcut: "+e.h);});b.length?d.forEach(function(e){e=e.toString();var g=new I0;e=e in a?a[e]:a[e]=g;R0(e.next,b.slice(0),c)}):d.forEach(function(e){a[e]=new I0(c)})},S0=function(a,b){for(var c=0;c<b.length;c++){var d=a[b[c]];if(d)return d}},T0=function(a,b,c){a:{var d=b.h;if(""!=b.C){var e=b.C;if("Control"==
e||"Shift"==e||"Meta"==e||"AltGraph"==e){d=!1;break a}}else if(16==d||17==d||18==d){d=!1;break a}e=b.O;var g="TEXTAREA"==e.tagName||"INPUT"==e.tagName||"BUTTON"==e.tagName||"SELECT"==e.tagName,h=!g&&(e.isContentEditable||e.ownerDocument&&"on"==e.ownerDocument.designMode);d=!g&&!h||a.K[d]||a.F?!0:h?!1:a.L&&(b.m||b.o||b.D)?!0:"INPUT"==e.tagName&&a.R[e.type]?13==d:"INPUT"==e.tagName||"BUTTON"==e.tagName?a.N?!0:32!=d:!1}if(d)if(!c&&Q0(b))a.o=!1;else{c=_ds.QB(b.h);d=N0(b.C,c,(b.G?1:0)|(b.o?2:0)|(b.m?4:
0)|(b.D?8:0));e=S0(a.m,d);if(!e||1500<=Date.now()-a.C)a.m=a.j,a.C=Date.now();(e=S0(a.m,d))&&e.next&&(a.m=e.next,a.C=Date.now());e&&(e.next?(0,b.j)():(a.m=a.j,a.C=Date.now(),a.G&&(0,b.j)(),a.J&&(0,b.J)(),d=e.h,e=a.dispatchEvent(new H0("shortcut",d,b.F)),(e&=a.dispatchEvent(new H0("shortcut_"+d,d,b.F)))||(0,b.j)(),_ds.Tn&&(a.D=c)))}},U0=function(a,b,c){for(;0<c.length&&b;){var d=c.shift();if((d=S0(b,d))&&(0==c.length&&d.h||U0(a,d.next,c.slice(0))))return!0}return!1},X0=function(a){_ds.Um.call(this);
this.m=this.j={};this.C=0;this.K=z0(V0);this.R=z0(W0);this.G=!0;this.F=this.J=!1;this.L=!0;this.N=!1;this.D=null;this.h=a;_ds.rh(this.h,"keydown",this.al,void 0,this);_ds.rh(this.h,"synthetic-keydown",this.jl,void 0,this);_ds.HJ&&(_ds.rh(this.h,"keypress",this.ql,void 0,this),_ds.rh(this.h,"synthetic-keypress",this.rl,void 0,this));_ds.rh(this.h,"keyup",this.bl,void 0,this);_ds.rh(this.h,"synthetic-keyup",this.ll,void 0,this)},Y0=function(a,b){return _ds.sg(a,10,b)},Z0=function(a){return(0,_ds.T)('<div class="devsite-popout" id="'+
_ds.X(a.id)+'"><div class="devsite-popout-result devsite-suggest-results-container" devsite-hide></div></div>')},$0=function(a){var b='<button type="submit" class="button button-white devsite-search-project-scope">';a=_ds.U(a)+"\uc758 \ubaa8\ub4e0 \uacb0\uacfc";return(0,_ds.T)(b+a+"</button>")},a1=function(a,b,c){var d='<button type="submit" class="button button-white devsite-suggest-all-results">';b?(a=_ds.U(c)+"\uc758 \ubaa8\ub4e0 \uacb0\uacfc",d+=a):(a="'"+_ds.U(a)+"'\uc5d0 \ub300\ud55c \ubaa8\ub4e0 \uacb0\uacfc",
d+=a);return(0,_ds.T)(d+"</button>")},b1=function(a,b,c,d,e,g,h,k){a=(c?"":'<devsite-analytics-scope action="'+_ds.X(_ds.Sj("Restricted "+d))+'">')+'<a class="devsite-result-item-link" href="'+_ds.X(_ds.Sj(a))+'"><span class="devsite-suggestion-fragment">'+_ds.U(b)+"</span>"+(k?'<span class="devsite-suggestion-fragment">'+_ds.U(k)+"</span>":"")+(e?'<span class="devsite-suggestion-fragment">'+_ds.U(e)+"</span>":"")+(_ds.sj(g)&&!h?'<span class="devsite-suggestion-fragment">'+_ds.U(g)+"</span>":"");
c||(a+='<span class="devsite-result-item-confidential">\uae30\ubc00</span>');return(0,_ds.T)(a+("</a>"+(c?"":"</devsite-analytics-scope>")))},c1=function(a){var b=a.projectName,c=a.hm,d=a.query,e=a.ym;a=a.Uf;b='<div class="devsite-suggest-wrapper '+(e?"":"devsite-search-disabled")+'"><div class="devsite-suggest-section"><div class="devsite-result-label">\uac80\uc0c9\uc5b4\uc5d0 \ub300\ud55c \ucd94\ucc9c \uac80\uc0c9\uc5b4\uac00 \uc5c6\uc2b5\ub2c8\ub2e4.</div></div>'+((e?'<div class="devsite-suggest-footer">'+
(c?$0(b):"")+a1(d,c,a)+"</div>":"")+"</div>");return(0,_ds.T)(b)},d1=function(a){var b=a.wr,c=a.Gr,d=a.Or,e=a.projectName,g=a.hm,h=a.query,k=a.Ur,l=a.ym;a=a.Uf;var m='<div class="devsite-suggest-wrapper '+(l?"":"devsite-search-disabled")+'" tabindex="0" role="list"><div class="devsite-suggest-section">';if(0<d.length){m=m+'<div class="devsite-suggest-sub-section" role="listitem"><div class="devsite-suggest-header" id="devsite-suggest-header-partial-query" role="heading" aria-level="2">\ucd94\ucc9c \uac80\uc0c9\uc5b4'+
((g?'<span class="devsite-suggest-project">'+_ds.U(e)+"</span>":"")+'</div><devsite-analytics-scope category="Site-Wide Custom Events" label="Search" role="list" aria-labelledby="devsite-suggest-header-partial-query" action="Query Suggestion Click">');for(var p=d.length,q=0;q<p;q++){var t=d[q];m+='<div class="devsite-result-item devsite-nav-label" id="suggestion-partial-query-'+_ds.X(q)+'" role="listitem" index=":'+_ds.X(q)+'">'+b1(t.Ra(),t.Ka(),_ds.qg(t,14),"Query Suggestion Click")+"</div>"}m+=
"</devsite-analytics-scope></div>"}m+=0<d.length&&0<b.length?'<hr role="none">':"";if(0<b.length){m=m+'<div class="devsite-suggest-sub-section" role="listitem"><div class="devsite-suggest-header" id="devsite-suggest-header-product" role="heading" aria-level="2">\ud398\uc774\uc9c0'+((g?'<span class="devsite-suggest-project">'+_ds.U(e)+"</span>":"")+'</div><devsite-analytics-scope category="Site-Wide Custom Events" label="Search" role="list" aria-labelledby="devsite-suggest-header-product" action="Page Suggestion Click">');
p=b.length;for(q=0;q<p;q++)t=b[q],m+='<div class="devsite-result-item devsite-nav-label" id="suggestion-product-'+_ds.X(q)+'" role="listitem" index=":'+_ds.X(q)+'">'+b1(t.Ra(),t.Ka(),_ds.qg(t,14),"Page Suggestion Click",void 0,_ds.O(t,4),g)+"</div>";m+="</devsite-analytics-scope></div>"}m+=0<k.length&&0<b.length+d.length?'<hr role="none">':"";if(0<k.length){m=m+'<div class="devsite-suggest-sub-section" role="listitem"><div class="devsite-suggest-header" id="devsite-suggest-header-reference" role="heading" aria-level="2">\ucc38\uc870'+
((g?'<span class="devsite-suggest-project">'+_ds.U(e)+"</span>":"")+'</div><devsite-analytics-scope category="Site-Wide Custom Events" label="Search" role="list" aria-labelledby="devsite-suggest-header-reference" action="Reference Suggestion Click">');p=k.length;for(q=0;q<p;q++)t=k[q],m+='<div class="devsite-result-item devsite-nav-label" id="suggestion-reference-'+_ds.X(q)+'" role="listitem" index=":'+_ds.X(q)+'">'+b1(t.Ra(),t.Ka(),_ds.qg(t,14),"Reference Suggestion Click",_ds.O(t,3),_ds.O(t,4),
g,_ds.I(t,10)[0])+"</div>";m+="</devsite-analytics-scope></div>"}m+=0<c.length&&0<b.length+d.length+k.length?'<hr role="none">':"";if(0<c.length){m+='<div class="devsite-suggest-sub-section" role="listitem"><div class="devsite-suggest-header" id="devsite-suggest-header-other-products" role="heading" aria-level="2"><span role="columnheader">\uc81c\ud488</span></div><devsite-analytics-scope category="Site-Wide Custom Events" label="Search" role="list" aria-labelledby="devsite-suggest-header-other-products" action="Product Suggestion Click">';
b=c.length;for(d=0;d<b;d++)k=c[d],m+='<div class="devsite-result-item devsite-nav-label" id="suggestion-other-products-'+_ds.X(d)+'" role="listitem" index=":'+_ds.X(d)+'">'+b1(k.Ra(),k.Ka(),_ds.qg(k,14),"Product Suggestion Click")+"</div>";m+="</devsite-analytics-scope></div>"}m+="</div>"+(l?'<div class="devsite-suggest-footer">'+(g?$0(e):"")+a1(h,g,a)+"</div>":"")+"</div>";return(0,_ds.T)(m)},e1=function(){var a=_ds.R.call(this)||this;a.V=!1;a.J={};a.K="";a.F=null;a.m=new _ds.Gl;a.j=null;a.N=!1;
return a},k1=function(a){a.j&&(a.m.listen(a.j,"suggest-service-search",function(b){a:{var c=a.D.querySelector(".highlight");if(c&&(c=c.querySelector(".devsite-result-item-link"))){c.click();break a}f1(a,b.detail.originalEvent,!!a.F)}}),a.m.listen(a.j,"suggest-service-suggestions-received",function(b){return void g1(a,b)}),a.m.listen(a.j,"suggest-service-focus",function(){h1(a,"cloud-track-search-focus",null);a.N=!0;i1(a,!0)}),a.m.listen(a.j,"suggest-service-blur",function(){i1(a,!1)}),a.m.listen(a.j,
"suggest-service-input",function(){!a.J["Text Entered Into Search Bar"]&&a.j.query.trim()&&(a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",label:"Search",action:"Text Entered Into Search Bar"},bubbles:!0})),a.J["Text Entered Into Search Bar"]=!0);a.N&&(h1(a,"cloud-track-search-input",null),a.N=!1)}),a.m.listen(a.j,"suggest-service-navigate",function(b){return void j1(a,b)}),a.m.listen(document.body,"devsite-page-changed",function(){return a.J=
{}}),a.j.Dm("SLASH",191));a.o&&a.m.listen(a.o,"submit",function(b){f1(a,b)});a.D&&a.m.listen(a.D,"click",function(b){var c=b.target,d=c.closest(".devsite-result-item-link");d&&(i1(a,!1),d="suggestion: "+d.getAttribute("href"),h1(a,"cloud-track-search-submit",d));c.classList.contains("devsite-search-project-scope")&&f1(a,b,!0)});a.Y&&a.m.listen(a.Y,"click",function(){return void i1(a,!0)});a.R&&a.m.listen(a.R,"click",function(){return void i1(a,!1)})},f1=function(a,b,c){c=void 0===c?!1:c;var d,e;_ds.bb(function(g){if(1==
g.h){b.preventDefault();b.stopPropagation();if(!a.hasAttribute("enable-search"))return g.H(0);a.J["Full Site Search"]||(a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",label:"Search",action:"Full Site Search"},bubbles:!0})),a.J["Full Site Search"]=!0);h1(a,"cloud-track-search-submit",a.L?"contains: "+a.L:"no match");d=c&&a.F?_ds.tm(a.F):_ds.tm(a.o.getAttribute("action"));e=new _ds.Hi(d.href);_ds.$i(e,"q",a.j.query);d.search=e.h.toString();
return _ds.y(g,DevsiteApp.fetchPage(d.href),3)}i1(a,!1);_ds.z(g)})},j1=function(a,b){var c=b.detail;b=a.C.querySelector(".highlight");var d,e=Array.from(a.C.querySelectorAll(".devsite-result-item")),g=[],h=-1;if(b){var k=_ds.ll(b,function(m){return m.classList.contains("devsite-suggest-section")});g=Array.from(k.querySelectorAll(".devsite-result-item"));k=_ds.Ok(b.parentNode.parentNode);var l=_ds.Pk(b.parentNode.parentNode);h=e.indexOf(b)}switch(c.keyCode){case 37:if(!k&&!l)return;b&&(c=b.getAttribute("index"),
l?(d=l.querySelector('[index="'+c+'"]'))||(d=_ds.Ib(Array.from(l.querySelectorAll("[index]")))):k&&((d=k.querySelector('[index="'+c+'"]'))||(d=_ds.Ib(Array.from(k.querySelectorAll("[index]"))))));break;case 39:if(!k&&!l)return;b&&(c=b.getAttribute("index"),k?(d=k.querySelector('[index="'+c+'"]'))||(d=_ds.Ib(Array.from(k.querySelectorAll("[index]")))):l&&((d=l.querySelector('[index="'+c+'"]'))||(d=_ds.Ib(Array.from(l.querySelectorAll("[index]"))))));break;case 38:b?(d=e[h-1])||(d=_ds.Ib(g)):d=_ds.Ib(e);
break;case 40:b?(d=e[h+1])||(d=g[0]):d=e[0]}b&&(b.classList.remove("highlight"),b.removeAttribute("aria-selected"));d&&(a.G.setAttribute("aria-activedescendant",d.id),d.setAttribute("aria-selected","true"),d.classList.add("highlight"),d.scrollIntoViewIfNeeded&&d.scrollIntoViewIfNeeded()||d.scrollIntoView())},h1=function(a,b,c){a.dispatchEvent(new CustomEvent(b,{detail:{type:"search",name:b,position:"nav",metadata:{eventDetail:c}},bubbles:!0}))},i1=function(a,b){if(a.V!==b){_ds.WB(a.j,b);if(a.V=b)a.setAttribute("search-active",
"");else{var c=a.D.querySelector(".highlight");c&&c.classList.remove("highlight");a.removeAttribute("search-active");a.setAttribute("aria-expanded","false");_ds.Gk(a.C)}a.hasAttribute("capture")||a.dispatchEvent(new CustomEvent("devsite-search-toggle",{detail:{active:b},bubbles:!0}))}},g1=function(a,b){a.L=null;b=b.detail;var c=b.suggestions,d=b.query;if(a.j.query.toLowerCase().startsWith(d.toLowerCase()))if(c){var e=c.Hb();0<e.length&&(b=e.filter(function(t){return t.Ka().includes(d)}),0<b.length&&
(a.L=b[0].Ka()));b=e.filter(function(t){return 2===t.rd()});c=e.filter(function(t){return 3===t.rd()});var g=e.filter(function(t){return 4===t.rd()}).slice(0,5),h=e.filter(function(t){return 1===t.rd()});e=b.length+g.length+h.length;for(var k=_ds.r(g),l=k.next();!l.done;l=k.next())l=l.value,l.Ad(_ds.tm((a.F||"/s/results")+"/?q="+l.Ka()).toString());var m=d.split(l1);c.forEach(function(t){return Y0(t,_ds.I(t,10).filter(function(u){return m.some(function(v){return u.includes(v)})}))});k=a.getAttribute("project-name")||
"";l=a.hasAttribute("project-scope");var p=a.hasAttribute("enable-search"),q=a.getAttribute("tenant-name")||"";b={wr:b,projectName:k,hm:l,Gr:h,Or:g,query:d,Ur:c,ym:p,Uf:q};0===e?_ds.sl(a.C,c1,b):(_ds.sl(a.C,d1,b),m1(a,d));a.setAttribute("aria-expanded","true");a.C.removeAttribute("hidden")}else a.C.setAttribute("hidden",""),a.setAttribute("aria-expanded","false")},m1=function(a,b){b=new RegExp("("+_ds.Rd(b)+")","ig");a=_ds.r(a.C.querySelectorAll(".devsite-suggestion-fragment"));for(var c=a.next();!c.done;c=
a.next()){c=c.value;var d=c.innerHTML;d=d.replace(b,"<b>$1</b>");d=_ds.EE(d);_ds.Gd(c,d)}},L0={8:"backspace",9:"tab",13:"enter",16:"shift",17:"ctrl",18:"alt",19:"pause",20:"caps-lock",27:"esc",32:"space",33:"pg-up",34:"pg-down",35:"end",36:"home",37:"left",38:"up",39:"right",40:"down",45:"insert",46:"delete",48:"0",49:"1",50:"2",51:"3",52:"4",53:"5",54:"6",55:"7",56:"8",57:"9",59:"semicolon",61:"equals",65:"a",66:"b",67:"c",68:"d",69:"e",70:"f",71:"g",72:"h",73:"i",74:"j",75:"k",76:"l",77:"m",78:"n",
79:"o",80:"p",81:"q",82:"r",83:"s",84:"t",85:"u",86:"v",87:"w",88:"x",89:"y",90:"z",93:"context",96:"num-0",97:"num-1",98:"num-2",99:"num-3",100:"num-4",101:"num-5",102:"num-6",103:"num-7",104:"num-8",105:"num-9",106:"num-multiply",107:"num-plus",109:"num-minus",110:"num-period",111:"num-division",112:"f1",113:"f2",114:"f3",115:"f4",116:"f5",117:"f6",118:"f7",119:"f8",120:"f9",121:"f10",122:"f11",123:"f12",186:"semicolon",187:"equals",189:"dash",188:",",190:".",191:"/",192:"`",219:"open-square-bracket",
220:"\\",221:"close-square-bracket",222:"single-quote",224:"win"};_ds.f=F0.prototype;_ds.f.keyCode=function(a){this.m=a;return this};_ds.f.key=function(a){this.o=a;return this};_ds.f.shiftKey=function(a){this.O=a;return this};_ds.f.altKey=function(a){this.h=a;return this};_ds.f.ctrlKey=function(a){this.j=a;return this};_ds.f.metaKey=function(a){this.C=a;return this};_ds.f.target=function(a){this.J=a;return this};_ds.yb(H0,_ds.dh);
var V0=[27,112,113,114,115,116,117,118,119,120,121,122,123,19],W0="color date datetime datetime-local email month number password search tel text time url week".split(" "),K0;_ds.yb(X0,_ds.Um);_ds.f=X0.prototype;_ds.f.w1=function(){return this.G};_ds.f.zja=function(a){this.J=a};_ds.f.z1=function(){return this.J};_ds.f.wja=function(a){this.F=a};_ds.f.q1=function(){return this.F};_ds.f.Lna=function(a){this.L=a};_ds.f.a6=function(){return this.L};_ds.f.yja=function(a){this.N=a};_ds.f.um=_ds.la(1);
_ds.f.Cra=function(a){J0(this.j,O0(0,arguments))};_ds.f.Bfa=function(a){return U0(this,this.j,O0(0,arguments))};_ds.f.ema=function(a){this.K=z0(a)};_ds.f.A4=function(){return _ds.$b(this.K)};
_ds.f.ua=function(){X0.Da.ua.call(this);this.j={};_ds.Bh(this.h,"keydown",this.al,!1,this);_ds.Bh(this.h,"synthetic-keydown",this.jl,!1,this);_ds.HJ&&(_ds.Bh(this.h,"keypress",this.ql,!1,this),_ds.Bh(this.h,"synthetic-keypress",this.rl,!1,this));_ds.Bh(this.h,"keyup",this.bl,!1,this);_ds.Bh(this.h,"synthetic-keyup",this.ll,!1,this);this.h=null};_ds.f.dM=function(a){return"shortcut_"+a};_ds.f.bl=function(a){a=G0(a);_ds.Tn&&P0(this,a);_ds.HJ&&!this.o&&Q0(a)&&T0(this,a,!0)};
_ds.f.ll=function(a){a=a.j();_ds.Tn&&P0(this,a);_ds.HJ&&!this.o&&Q0(a)&&T0(this,a,!0)};_ds.f.ql=function(a){a=G0(a);32<a.h&&Q0(a)&&(this.o=!0)};_ds.f.rl=function(a){a=a.j();32<a.h&&Q0(a)&&(this.o=!0)};_ds.f.al=function(a){T0(this,G0(a))};_ds.f.jl=function(a){T0(this,a.j())};
_ds.XB.prototype.Dm=_ds.ma(2,function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];var e=this;this.h&&this.h.dispose();a&&(this.h=new X0(document),this.h.G=!1,this.h.um.apply(this.h,[a].concat(_ds.ya(c))),this.eventHandler.listen(this.h,"shortcut",function(g){var h=document;h.activeElement&&h.activeElement===h.body&&(g.preventDefault(),_ds.WB(e,!0))}))});X0.prototype.um=_ds.ma(1,function(a,b){R0(this.j,O0(1,arguments),a)});var l1=/[ .()<>{}\[\]\/:,]+/,n1=0;_ds.w(e1,_ds.R);e1.prototype.disconnectedCallback=function(){_ds.Ml(this.m);this.j&&(this.j.dispose(),this.j=null)};e1.prototype.attributeChangedCallback=function(a,b,c){switch(a){case "project-scope":this.K=c||"";this.j&&(this.j.K=this.K);break;case "url-scoped":this.F=c;break;case "disabled":this.G&&(this.G.disabled=null!==c)}};
e1.prototype.connectedCallback=function(){if(this.o=this.querySelector("form")){this.G=this.o.querySelector(".devsite-search-query");this.Y=this.o.querySelector(".devsite-search-button[search-open]");this.R=this.querySelector(".devsite-search-button[search-close]");var a="devsite-search-popout-container-id-"+ ++n1;this.G.setAttribute("aria-controls",a);this.D=_ds.vl(Z0,{id:a});this.C=this.D.querySelector(".devsite-suggest-results-container");this.o.appendChild(this.D);this.hasAttribute("project-scope")&&
(this.K=this.getAttribute("project-scope"));this.hasAttribute("url-scoped")&&(this.F=this.getAttribute("url-scoped"));this.o&&this.G&&(this.j=new _ds.XB(this,this.o,this.G),this.j.m=!0,this.j.Fh=this.hasAttribute("enable-query-completion"),this.j.uf=!0,this.j.Eh=!0,this.j.Gh=!0,this.j.K=this.K,this.j.m=this.hasAttribute("enable-suggestions"));k1(this)}};e1.prototype.$=function(a){var b=this;_ds.ll(a.target,function(c){return c===b})||i1(this,!1)};
_ds.n.Object.defineProperties(e1,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["project-scope","url-scoped","disabled"]}}});e1.prototype.connectedCallback=e1.prototype.connectedCallback;e1.prototype.attributeChangedCallback=e1.prototype.attributeChangedCallback;e1.prototype.disconnectedCallback=e1.prototype.disconnectedCallback;try{window.customElements.define("devsite-search",e1)}catch(a){console.warn("devsite.app.customElement.DevsiteSearch",a)};})(_ds_www);
