(function(_ds){var window=this;'use strict';var SR=function(){var a=void 0===a?_ds.EK.length:a;return _ds.EK.slice(0,a)},TR=function(a){var b=a.projectName,c=a.Jr,d=a.Kr,e=a.Pp,g=a.Ap,h=a.Ls;a='<devsite-dialog class="devsite-feedback"><div class="devsite-dialog-contents"><h3 class="no-link">\ub2e4\uc74c\uc5d0 \ub300\ud55c \uc758\uacac \ubcf4\ub0b4\uae30...</h3><div class="devsite-feedback-items"><a href="#" class="devsite-feedback-item" feedback-type="documentation" data-label="Docs Feedback Image" track-type="feedback" track-name="feedbackDocIcon"><div class="devsite-feedback-item-icon-container devsite-feedback-item-icon-color"><div class="devsite-feedback-item-icon material-icons" aria-hidden="true">description</div></div><div>\uc774 \ud398\uc774\uc9c0</div><div class="devsite-feedback-item-type">\ubb38\uc11c\uc5d0 \ub300\ud55c \uc758\uacac</div></a>';
g||(c=d?'<div class="devsite-feedback-item-icon material-icons" aria-hidden="true">'+_ds.U(d)+"</div>":c?'<img src="'+_ds.X(_ds.Uj(c))+'" loading="lazy" alt="">':"",a+="<a"+(e?' href="'+_ds.X(_ds.Sj(e))+'"':' href="#"')+' class="devsite-feedback-item" feedback-type="product" data-label="Product Feedback Image" track-type="feedback" track-name="feedbackProductIcon"><div class="devsite-feedback-item-icon-container '+(d?"devsite-feedback-item-icon-color devsite-theme-primary":"devsite-feedback-item-icon-img")+
'">'+c+"</div><div>"+_ds.U(b)+'</div><div class="devsite-feedback-item-type">',a+="\uc81c\ud488\uc5d0 \ub300\ud55c \uc758\uacac</div></a>");a+='</div><div class="devsite-feedback-notice">\uc758\uacac\uc744 \ubcf4\ub0b4\uc8fc\uc154\uc11c \uac10\uc0ac\ud569\ub2c8\ub2e4. \ub2f5\ubcc0\ud574 \ub4dc\ub9b4 \uc218\ub294 \uc5c6\uc73c\ub2c8 \uc591\ud574\ud574 \uc8fc\uc138\uc694.</div>';h&&(a+='<div class="devsite-feedback-support"><span class="devsite-feedback-support-icon material-icons" aria-hidden="true">help</span><span>',
b='\ub3c4\uc6c0\uc774 \ud544\uc694\ud558\uc2e0\uac00\uc694? <a href="'+(_ds.X(_ds.Sj(h))+'">\uc9c0\uc6d0 \ud398\uc774\uc9c0</a>\ub97c \ubc29\ubb38\ud558\uc138\uc694.'),a=a+b+"</span></div>");return(0,_ds.T)(a+'<div class="devsite-feedback-buttons"><button class="button-white" tabindex="1" data-label="Cancel Feedback Button" track-type="feedback" track-name="cancelFeedbackButton" feedback-cancel>\ub2eb\uae30</button></div></div></devsite-dialog>')},dS=function(){var a=_ds.R.call(this,["devsite-dialog"])||
this;a.eventHandler=new _ds.Gl;a.j=null;a.m=!1;a.O(_ds.Jh(UR),_ds.Jh(VR),_ds.Jh(WR),_ds.Jh(YR),_ds.Jh(ZR),_ds.Jh($R),_ds.Jh(aS),_ds.Jh(bS),_ds.Jh(cS));return a},iS=function(a){var b;a.eventHandler.listen(a,"click",function(e){if("A"===e.target.tagName||"BUTTON"===e.target.tagName)e.preventDefault(),e.stopPropagation(),a.j&&(document.body.appendChild(a.j),_ds.vo.Vb([_ds.Jh(eS)],a.j,"open",""),e={action:"click",category:a.getAttribute("data-category")||"Site-Wide Custom Events",label:a.getAttribute("data-label")},
fS(a,e))});if(a.j){var c=Array.from(a.j.querySelectorAll("[feedback-type]"));c=_ds.r(c);for(var d=c.next();!d.done;d=c.next())a.eventHandler.listen(d.value,"click",function(e){gS(a,e)});(c=null===(b=a.j)||void 0===b?void 0:b.querySelector("button[feedback-cancel]"))&&a.eventHandler.listen(c,"click",function(){hS(a);var e,g=null===(e=a.j)||void 0===e?void 0:e.querySelector("button[feedback-cancel]");e={action:"click",label:null===g||void 0===g?void 0:g.getAttribute("data-label"),category:(null===g||
void 0===g?void 0:g.getAttribute("data-category"))||"Site-Wide Custom Events"};fS(a,e)});a.eventHandler.listen(a.j,"devsite-dialog-hide",function(){_ds.Kk(a.j)})}},gS=function(a,b){var c=b.Nc,d=c.getAttribute("feedback-type"),e="#"===c.getAttribute("href");d={context:a.getAttribute("context"),type:d};var g=SR();g.length&&(d.errorStack=g);a.hasAttribute("rating-type")&&(d.ratingType=a.getAttribute("rating-type"));a.hasAttribute("rating-category")&&(d.ratingCategory=a.getAttribute("rating-category"));
g={productId:a.getAttribute("product-id"),locale:DevsiteApp.getLocale(),bucket:a.getAttribute("bucket"),productVersion:a.getAttribute("version"),callback:function(){return void jS()},onLoadCallback:function(){return void hS(a)}};c={action:"click",label:c.getAttribute("data-label"),category:c.getAttribute("data-category")||"Site-Wide Custom Events"};fS(a,c);e&&(b.preventDefault(),b.stopPropagation(),_ds.$C(g,d))},hS=function(a){var b;null===(b=a.j)||void 0===b?void 0:b.removeAttribute("open");_ds.Kk(a.j)},
jS=function(){Array.from(document.querySelectorAll('script[src*="www.google.com/tools/feedback/"]')).forEach(function(a){return _ds.Kk(a)})},fS=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:b,bubbles:!0}))};var UR=_ds.xa(["bucket"]),VR=_ds.xa(["context"]),WR=_ds.xa(["product-id"]),YR=_ds.xa(["data-label"]),ZR=_ds.xa(["track-metadata-position"]),$R=_ds.xa(["track-name"]),aS=_ds.xa(["track-type"]),bS=_ds.xa(["disable"]),cS=_ds.xa(["project-"]),eS=_ds.xa(["open"]);_ds.w(dS,_ds.R);
dS.prototype.connectedCallback=function(){if(!this.m){var a=this.querySelector(".google-feedback"),b=new Map([["data-b","bucket"],["data-context","context"],["data-p","product-id"]]),c=new Map([["data-label","Send Feedback Button"],["track-metadata-position","content"],["track-name","sendFeedbackLink"],["track-type","feedback"]]);if(a){b=_ds.r(b.entries());for(var d=b.next();!d.done;d=b.next()){var e=_ds.r(d.value);d=e.next().value;e=e.next().value;if(a.hasAttribute(d)){var g=a.getAttribute(d)||"";
_ds.ai(this,e,g);a.removeAttribute(d)}}c=_ds.r(c.entries());for(b=c.next();!b.done;b=c.next())d=_ds.r(b.value),b=d.next().value,d=d.next().value,a.hasAttribute(b)?(d=a.getAttribute(b)||"",_ds.ai(this,b,d),a.removeAttribute(b)):_ds.ai(this,b,d);a.classList.remove("google-feedback")}!this.hasAttribute("project-name")&&(a=document.querySelector('meta[property="og:site_name"]'))&&(a=a.getAttribute("content")||"",_ds.ai(this,"project-name",a));this.hasAttribute("project-icon")?_ds.ai(this,"project-icon",
_ds.tm(this.getAttribute("project-icon")||"").href||""):(a=document.querySelector('link[rel="apple-touch-icon"]'))&&_ds.ai(this,"project-icon",a.getAttribute("href")||"");this.j=_ds.vl(TR,{Ap:this.hasAttribute("disable-product-feedback"),Pp:this.getAttribute("project-feedback-url"),Jr:this.getAttribute("project-icon"),Kr:this.getAttribute("project-icon-name"),projectName:this.getAttribute("project-name")||"",Ls:this.getAttribute("project-support-url")});this.m=!0}iS(this)};
dS.prototype.disconnectedCallback=function(){_ds.Ml(this.eventHandler)};dS.prototype.disconnectedCallback=dS.prototype.disconnectedCallback;dS.prototype.connectedCallback=dS.prototype.connectedCallback;try{window.customElements.define("devsite-feedback",dS)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteFeedback",a)};})(_ds_www);
