(function(_ds){var window=this;'use strict';var rQ=function(){var a=_ds.R.call(this)||this;a.C=new _ds.Gl;a.D=new _ds.Gl;a.m=new Set;a.j=null;"IntersectionObserver"in window&&(a.j=new IntersectionObserver(function(b){b=_ds.r(b);for(var c=b.next();!c.done;c=b.next())c=c.value,c.isIntersecting&&(c=c.target,_ds.IE(new _ds.GE,c),a.m.delete(c),a.j.unobserve(c))},{rootMargin:"100%"}));return a},sQ=function(a){Array.from(a.getElementsByTagName("table")).forEach(function(b){if(!b.parentNode.classList.contains("devsite-table-wrapper")){var c=
document.createElement("div");c.classList.add("devsite-table-wrapper");b.classList.contains("full-width")&&(c.classList.add("devsite-full-width-table"),b.classList.remove("full-width"));_ds.Hk(c,b);c.appendChild(b)}})},AQ=function(a,b){var c,d,e,g,h,k,l;return _ds.bb(function(m){if(1==m.h)return _ds.y(m,DevsiteApp.whenReady(),2);c=_ds.lm();d=DevsiteApp.getInsecureHost();e=b.ma;if(e.origin!==c.origin&&d&&e.origin!==d)return m.return();try{g=_ds.Ig(_ds.Bo,e.data)}catch(p){return m.return()}h=_ds.pg(g,
1,0);if(4===h)return tQ(a,e),m.return();k=g.getName();if(!k)return m.return();if(l=a.querySelector('devsite-iframe iframe[name="'+k+'"]'))switch(h){case 5:uQ(g,l);break;case 8:vQ(e,g,c);break;case 1:wQ(e,g,c);break;case 6:case 7:xQ(h,c,g);break;case 9:yQ(a,g);break;case 10:zQ(g,c)}_ds.z(m)})},uQ=function(a,b){var c,d,e,g;_ds.bb(function(h){c=_ds.xk(document).y;d=_ds.Mg(a,4);e=_ds.Mg(a,3);g=_ds.Sk(b);d&&g.setAttribute("width",d+"px");e&&g.setAttribute("height",e+"px");window.requestAnimationFrame(function(){window.scrollTo(_ds.xk(document).x,
c)});_ds.z(h)})},tQ=function(a,b){var c,d,e;_ds.bb(function(g){if(c=BQ(a,b.source)){d="goog_"+_ds.No++;c.setAttribute("name",d);var h=_ds.Co(3);e=_ds.P(h,2,d);(h=b.source)&&h.postMessage(_ds.Hg(e),"*")}_ds.z(g)})},vQ=function(a,b,c){var d;_ds.bb(function(e){var g=_ds.Do(_ds.Co(8),_ds.O(b,8));d=_ds.P(g,6,c.toString());(g=a.source)&&g.postMessage(_ds.Hg(d),"*");_ds.z(e)})},wQ=function(a,b,c){var d;_ds.bb(function(e){var g=_ds.Do(_ds.Co(2),_ds.O(b,8));d=_ds.P(g,7,c.search+c.hash);(g=a.source)&&g.postMessage(_ds.Hg(d),
"*");_ds.z(e)})},xQ=function(a,b,c){var d,e,g;_ds.bb(function(h){d=c.Ka();e=new URL(c.getUrl(),b.origin);g=window.location.origin+window.location.pathname+e.search+e.hash;6===a?window.history.pushState({},d,g):window.history.replaceState({},d,g);_ds.z(h)})},yQ=function(a,b){var c,d,e,g;_ds.bb(function(h){c=_ds.O(b,9);d=JSON.parse(_ds.O(b,10));"cloudtrackEvent"===c&&d?(e=d,g={eventData:e},a.dispatchEvent(new CustomEvent("devsite-analytics-observation-cloudtrack",{detail:g,bubbles:!0}))):"devsite-apix"===
c&&a.dispatchEvent(new CustomEvent("devsite-apix-observation",{detail:d,bubbles:!0}));_ds.z(h)})},zQ=function(a,b){var c,d;_ds.bb(function(e){if(c=a.getUrl())d=new URL(c,b.origin),c.startsWith("#")||b.origin===d.origin&&b.pathname===d.pathname&&b.search===d.search?DevsiteApp.scrollToAnchor(d.hash,!0):DevsiteApp.fetchPage(d.href);_ds.z(e)})},BQ=function(a,b){var c;Array.from(a.querySelectorAll("devsite-iframe iframe")).forEach(function(d){_ds.al(d)===b&&(c=d)});return c},EQ=function(a){a.o=a.querySelector(".devsite-article-body");
a.o&&CQ(a);a.j&&a.j.disconnect();a.m.clear();sQ(a);var b=Array.from(a.querySelectorAll(".devsite-nav-title, .devsite-page-title, td > code, th > code"));if("docs"===document.body.getAttribute("layout")&&a.o){var c=Array.from(a.o.querySelectorAll("h1, h2, h3, h4, h5, h6"));b.push.apply(b,_ds.ya(c))}a.m.clear();a.m=new Set(b);if(_ds.lm().hash){b=new _ds.GE;c=_ds.r(a.m);for(var d=c.next();!d.done;d=c.next())_ds.IE(b,d.value)}else DQ(a,a.m);a.dispatchEvent(new CustomEvent("devsite-content-updated",{bubbles:!0}))},
CQ=function(a){"full"===document.body.getAttribute("layout")&&(a=a.o.querySelectorAll('h1[tabindex="0"],h2[tabindex="0"],h3[tabindex="0"],h4[tabindex="0"],h5[tabindex="0"],h6[tabindex="0"]'))&&Array.from(a).forEach(function(b){b.removeAttribute("tabindex")})},DQ=function(a,b){a.j&&b.forEach(function(c){a.j.observe(c)})};_ds.w(rQ,_ds.R);rQ.prototype.connectedCallback=function(){var a=this;this.C.listen(window,"message",function(b){return AQ(a,b)});EQ(this)};
rQ.prototype.disconnectedCallback=function(){this.j&&this.j.disconnect();this.m.clear();_ds.Ml(this.C);_ds.Ml(this.D)};rQ.prototype.Wa=function(a){var b=this;a&&([".devsite-article",".devsite-content-data","devsite-content-footer","devsite-google-survey"].forEach(function(c){_ds.bi(b,b.querySelector(c),a.querySelector(c))}),EQ(this))};rQ.prototype.updateContent=rQ.prototype.Wa;rQ.prototype.disconnectedCallback=rQ.prototype.disconnectedCallback;rQ.prototype.connectedCallback=rQ.prototype.connectedCallback;try{window.customElements.define("devsite-content",rQ)}catch(a){console.warn("devsite.app.customElement.DevsiteContent",a)};})(_ds_www);
