(function(_ds){var window=this;'use strict';var CO=function(a,b){a.href=_ds.Vh(b)},DO=function(){return(0,_ds.T)('<button class="devsite-book-nav-toggle" aria-haspopup="menu"><span class="material-icons devsite-book-nav-toggle-icon"></span></button>')},EO=function(){return(0,_ds.T)('<div class="devsite-book-nav-blur"></div>')},GO=function(){var a=_ds.R.call(this)||this;a.o=!1;a.m=null;a.eventHandler=new _ds.Gl;a.G=function(){};a.C=new Set;a.J=!1;a.background=document.createElement("div");a.background.classList.add("devsite-book-nav-bg");
a.j=_ds.vl(DO);a.D=_ds.vl(EO);a.K=new Promise(function(b){a.G=b});a.F=new _ds.Ln(function(){a.o&&FO(a)},20);return a},IO=function(a,b,c){c=void 0===c?!0:c;b=Array.from((void 0===b?a:b).querySelectorAll(".devsite-nav-title"));a.C=new Set(b);if(!_ds.lm().hash&&c)HO(a,a.C);else for(c=new _ds.GE,a=_ds.r(a.C),b=a.next();!b.done;b=a.next())_ds.IE(c,b.value)},HO=function(a,b){_ds.Q(a,function d(){var e=this,g,h,k,l,m,p,q;return _ds.D(d,function(t){if(1==t.h)return g=e,e.o?_ds.y(t,(0,_ds.Dp)(),2):t.return();
h=t.j;k=new _ds.GE;l=function(u){u=u.target;_ds.IE(k,u);g.C.delete(u);h.unregisterIntersectionForElement(u)};m=_ds.r(b);for(p=m.next();!p.done;p=m.next()){q=p.value;try{h.registerIntersectionForElement(q,l)}catch(u){l({target:q})}}_ds.z(t)})})},FO=function(a){var b=0<a.querySelectorAll(".devsite-nav-item").length,c=document.querySelector("#devsite-hamburger-menu");c&&(b?c.removeAttribute("visually-hidden"):_ds.ai(a,"visually-hidden","",c))},NO=function(a){a.eventHandler.listen(a,"click",function(b){var c;
if(!b.defaultPrevented){var d=b.target;"devsite-close-nav"===d.getAttribute("id")&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.hasAttribute("top-level-nav")?a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})):_ds.ai(a,"top-level-nav",""));if(d.hasAttribute("menu")){var e=d.getAttribute("menu");e&&JO(a,e)&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.removeAttribute("top-level-nav"))}if(!(d.classList.contains("devsite-nav-toggle")||d.classList.contains("devsite-nav-title-no-path")||
(null===(c=d.parentElement)||void 0===c?0:c.classList.contains("devsite-nav-title-no-path")))){a.m&&(b=a.m.querySelector("[menu=_book]"))&&b.contains(d)&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0}));var g;d instanceof Element&&d.matches("a.devsite-nav-title")?g=d:g=_ds.ml(d,"a","devsite-nav-title");g&&!g.classList.contains("devsite-nav-has-children")&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0}))}}});a.eventHandler.listen(a,[KO,"focusin"],function(b){return void LO(a,
b)});a.eventHandler.listen(document.body,"devsite-sitemask-hidden",function(){a.m&&(JO(a,"_book")?a.removeAttribute("top-level-nav"):_ds.ai(a,"top-level-nav",""))});a.eventHandler.listen(document.body,"devsite-page-loaded",function(){return void a.F.Aa()});a.eventHandler.listen(a,"devsite-content-updated",function(){a.F.Aa()});a.eventHandler.listen(a,"scroll",function(){_ds.ai(a,"user-scrolled","")});a.eventHandler.listen(a.j,"click",function(){MO(a)})},JO=function(a,b){var c=!1;if(a.m)for(var d=
_ds.r(a.m.querySelectorAll("[menu]")),e=d.next();!e.done;e=d.next())e=e.value,e.getAttribute("menu")===b?(e.removeAttribute("hidden"),c=!0):_ds.ai(a,"hidden","",e);return c},LO=function(a,b){b.defaultPrevented||(b=_ds.ll(b.target,function(c){return c instanceof HTMLAnchorElement&&c.hasAttribute("href")||c===a},!0),b!==a&&CO(b,_ds.bp(_ds.tm(b.href).href)))},PO=function(a){return _ds.Q(a,function c(){var d=this;return _ds.D(c,function(e){switch(e.h){case 1:if(!d.o)return e.return();d.removeAttribute("user-scrolled");
return _ds.y(e,_ds.Em(),2);case 2:return _ds.y(e,OO(d),3);case 3:return _ds.y(e,d.K,4);case 4:return _ds.y(e,(0,_ds.Dp)(),5);case 5:return _ds.y(e,_ds.Em(),6);case 6:return _ds.y(e,OO(d),0)}})})},QO=function(a,b){(b=void 0===b?a:b)||(b=a);var c=_ds.r(b.querySelectorAll(".devsite-nav-active"));for(a=c.next();!a.done;a=c.next())a.value.classList.remove("devsite-nav-active");a=_ds.Jm(_ds.lm().pathname);a='[href="'+_ds.tm(a).href+'"], [href="'+a+'"],\n        [alt-paths~="'+a+'"]';b=_ds.r(b.querySelectorAll(a));
for(a=b.next();!a.done;a=b.next())a.value.classList.add("devsite-nav-active")},RO=function(a,b){(b=void 0===b?a:b)||(b=a);var c=b.querySelector(".devsite-mobile-nav-bottom");if(c)for(var d=c.querySelector(".devsite-nav-active");d&&d.parentElement&&d.parentElement!==b;)d.hasAttribute("collapsed")&&(d.removeAttribute("animatable"),_ds.Kl(a.eventHandler,d,"devsite-expandable-nav-transition-end",function(){d&&_ds.ai(a,"animatable","",d)}),d.removeAttribute("collapsed")),d=d.parentElement},OO=function(a){return _ds.Q(a,
function c(){var d=this,e;return _ds.D(c,function(g){if(1==g.h)return d.o&&d.m?_ds.y(g,(0,_ds.Dp)(),2):g.return();if(4!=g.h)return(e=d.m.querySelector(".devsite-nav-active"))?d.hasAttribute("user-scrolled")?g.H(4):_ds.y(g,SO(d,e),4):g.H(0);_ds.ai(d,"animatable","");_ds.z(g)})})},SO=function(a,b){return _ds.Q(a,function d(){var e=this,g,h;return _ds.D(d,function(k){if(1==k.h){if(!e.o)return k.return();g=e.hasAttribute("user-scrolled");h=_ds.ao(b,e,!0);e.scrollTop=h.y;return _ds.y(k,_ds.Em(),2)}g&&
_ds.ai(e,"user-scrolled","");_ds.z(k)})})},TO=function(a){return _ds.Q(a,function c(){var d,e=this,g,h,k;return _ds.D(c,function(l){if(1==l.h)return _ds.y(l,(0,_ds.Dp)(),2);d=l.j;g=_ds.r(e.C);for(h=g.next();!h.done;h=g.next())k=h.value,d.unregisterIntersectionForElement(k);_ds.z(l)})})},MO=function(a){_ds.Q(a,function c(){var d,e,g=this;return _ds.D(c,function(h){if(1==h.h)return e=(d=document.documentElement.scrollHeight-document.documentElement.clientHeight)?document.documentElement.scrollTop/d:
0,g.hasAttribute("collapsed")?(_ds.ai(g,"aria-expanded","true",g.j),_ds.ai(g,"aria-label","\uce21\uba74 \ud0d0\uc0c9 \uc228\uae30\uae30",g.j),_ds.ai(g,"data-title","\uce21\uba74 \ud0d0\uc0c9 \uc228\uae30\uae30",g.j),g.removeAttribute("collapsed"),UO(g,"Expanded book nav")):(g.j.removeAttribute("aria-expanded"),_ds.ai(g,"aria-label","\uce21\uba74 \ud0d0\uc0c9 \ud45c\uc2dc",g.j),_ds.ai(g,"data-title","\uce21\uba74 \ud0d0\uc0c9 \ud45c\uc2dc",g.j),_ds.ai(g,"collapsed",""),UO(g,"Collapsed book nav")),
_ds.y(h,_ds.Em(),2);d=document.documentElement.scrollHeight-document.documentElement.clientHeight;document.documentElement.scrollTop=Math.round(e*d);_ds.z(h)})})},UO=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",action:"click",label:b},bubbles:!0}))};var VO=_ds.xa(["animatable"]),WO=_ds.xa(["aria-expanded"]),XO=_ds.xa(["aria-label"]),YO=_ds.xa(["collapsed"]),ZO=_ds.xa(["data-title"]),$O=_ds.xa(["fixed"]),aP=_ds.xa(["has-book-nav"]),bP=_ds.xa(["hidden"]),cP=_ds.xa(["role"]),dP=_ds.xa(["top-level-nav"]),eP=_ds.xa(["user-scrolled"]),fP=_ds.xa(["visually-hidden"]),KO="onpointerover"in window?"pointerover":"mouseover";_ds.w(GO,_ds.R);_ds.f=GO.prototype;
_ds.f.connectedCallback=function(){var a,b;return _ds.Q(this,function d(){var e=this,g;return _ds.D(d,function(h){if(1==h.h)return e.o=!0,e.O(e.h(VO),e.h(WO),e.h(XO),e.h(YO),e.h(ZO),e.h($O),e.h(aP),e.h(bP),e.h(cP),e.h(dP),e.h(eP),e.h(fP)),_ds.ai(e,"role","menu"),_ds.Hk(e.background,e),e.hasAttribute("hidden")&&(_ds.ai(e,"hidden","",e.j),_ds.ai(e,"hidden","",e.D)),_ds.y(h,(0,_ds.Dp)(),2);if(3!=h.h)return g=h.j,e.J=g.hasFlagAccess(150),e.J&&(null===(a=e.parentElement)||void 0===a?void 0:a.insertBefore(e.j,
e.nextSibling),_ds.ai(e,"aria-label","\uce21\uba74 \ud0d0\uc0c9 \uc228\uae30\uae30",e.j),_ds.ai(e,"data-title","\uce21\uba74 \ud0d0\uc0c9 \uc228\uae30\uae30",e.j),_ds.ai(e,"aria-expanded","true",e.j),null===(b=e.parentElement)||void 0===b?void 0:b.insertBefore(e.D,e.nextSibling)),FO(e),NO(e),_ds.y(h,e.init(),3);IO(e);_ds.z(h)})})};
_ds.f.disconnectedCallback=function(){this.o=!1;_ds.Ml(this.eventHandler);TO(this);this.C.clear();var a=document.querySelector("#devsite-hamburger-menu");a&&_ds.ai(this,"visually-hidden","",a);a=_ds.r([this.background,this.j,this.D]);for(var b=a.next();!b.done;b=a.next())(b=b.value)&&_ds.Kk(b);this.removeAttribute("animatable");document.body.style.removeProperty("--devsite-js-book-nav-scrollbar-width")};
_ds.f.attributeChangedCallback=function(a){"hidden"===a&&this.dispatchEvent(new CustomEvent(this.hasAttribute("hidden")?"devsite-element-hidden":"devsite-element-visible",{bubbles:!0}));if("hidden"===a||"collapsed"===a){var b=document.querySelector(".devsite-main-content");b&&(this.hasAttribute("collapsed")||this.hasAttribute("hidden")?b.removeAttribute("has-book-nav"):_ds.ai(this,"has-book-nav","",b))}if("fixed"===a||"hidden"===a||"collapsed"===a){b=this.hasAttribute(a);for(var c=_ds.r([this.background,
this.j,this.D]),d=c.next();!d.done;d=c.next())(d=d.value)&&(b?_ds.ai(this,a,"",d):d.removeAttribute(a))}"fixed"===a&&this.G()};
_ds.f.init=function(a){a=void 0===a?!0:a;return _ds.Q(this,function c(){var d=this,e,g,h;return _ds.D(c,function(k){if(1==k.h){if(!d.o)return k.return();document.body.style.setProperty("--devsite-js-book-nav-scrollbar-width",d.offsetWidth-d.clientWidth+"px");d.m=d.querySelector(".devsite-mobile-nav-bottom");!d.hasAttribute("hidden")&&d.m&&d.m.querySelector(".devsite-nav-active")||_ds.ai(d,"animatable","");_ds.ai(d,"top-level-nav","");d.m&&d.m.querySelector("[menu=_book]")&&d.removeAttribute("top-level-nav");
0===d.children.length&&_ds.ai(d,"hidden","");if(d.background)for(e=_ds.r(["hidden","fixed","animatable"]),g=e.next();!g.done;g=e.next())h=g.value,d.hasAttribute(h)&&_ds.ai(d,h,"",d.background);return!d.hasAttribute("hidden")&&a?(QO(d),RO(d),_ds.y(k,PO(d),0)):_ds.y(k,_ds.Em(),4)}return _ds.y(k,OO(d),0)})})};
_ds.f.Wa=function(a){return _ds.Q(this,function c(){var d=this,e;return _ds.D(c,function(g){switch(g.h){case 1:if(!a){_ds.Gk(d);g.H(2);break}d.removeAttribute("animatable");e=a.querySelector("nav")||null;QO(d,e);RO(d,e);if(!e){g.H(3);break}return _ds.y(g,TO(d),4);case 4:d.C.clear(),IO(d,e,!1);case 3:_ds.bi(d,d.querySelector("nav"),e);case 2:return _ds.y(g,_ds.Em(),5);case 5:return _ds.y(g,d.init(!1),0)}})})};
_ds.n.Object.defineProperties(GO,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["collapsed","fixed","hidden"]}}});GO.prototype.updateContent=GO.prototype.Wa;GO.prototype.attributeChangedCallback=GO.prototype.attributeChangedCallback;GO.prototype.disconnectedCallback=GO.prototype.disconnectedCallback;GO.prototype.connectedCallback=GO.prototype.connectedCallback;try{window.customElements.define("devsite-book-nav",GO)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteBookNav",a)};})(_ds_www);
