(function(_ds){var window=this;'use strict';var VP=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(_ds.mb(d)){var e=a.length||0,g=d.length||0;a.length=e+g;for(var h=0;h<g;h++)a[e+h]=d[h]}else a.push(d)}},WP=function(){var a=new _ds.iE;VP(a.L,"data-devsite-credential-type data-modal-dialog-id data-scope data-terminal-prefix data-title data-type".split(" "));return a},XP=function(){var a=WP();["devsite-var"].forEach(function(b){this.K.push(b)},a);return a},YP=function(){var a='<div class="devsite-code-buttons-container" role="group" aria-label="'+
_ds.wj("\uc791\uc5c5 \ubc84\ud2bc");return(0,_ds.T)(a+'"></div>')},ZP=function(a){a=a.label;return(0,_ds.T)('<button type="button" class="gc-analytics-event material-icons devsite-icon-code-dark devsite-toggle-dark" data-category="Site-Wide Custom Events" data-label="Dark Code Toggle" track-type="exampleCode" track-name="darkCodeToggle" aria-label="'+_ds.X(a)+'" data-title="'+_ds.X(a)+'"></button>')},$P=function(a){a=a.label;return(0,_ds.T)('<button type="button" class="gc-analytics-event material-icons devsite-icon-code-light devsite-toggle-light" data-category="Site-Wide Custom Events" data-label="Light Code Toggle" track-type="exampleCode" track-name="lightCodeToggle" aria-label="'+
_ds.X(a)+'" data-title="'+_ds.X(a)+'"></button>')},aQ=function(a){var b=a.label;return(0,_ds.T)('<button type="button" class="gc-analytics-event material-icons devsite-icon-copy" data-category="Site-Wide Custom Events" data-label="'+_ds.X(a.np)+'" track-type="exampleCode" track-name="clickToCopy" aria-label="'+_ds.X(b)+'" data-title="'+_ds.X(b)+'"></button>')},bQ=function(a){a=a.label;return(0,_ds.T)('<button type="button" class="gc-analytics-event material-icons devsite-icon-code" data-category="jsfiddle" data-label="" track-type="exampleCode" track-name="jsfiddle" aria-label="'+
_ds.X(a)+'" data-title="'+_ds.X(a)+'"></button>')},cQ=function(){var a=_ds.R.call(this,["devsite-snackbar"])||this;a.j=null;a.o=null;a.K="";a.D=null;a.m=new _ds.Gl;a.L=!1;a.C=null;a.F=null;a.N=new _ds.On;a.V=new _ds.mE(_ds.sE(XP()));a.G=null;a.J=new _ds.Rl;return a},dQ=function(a){Array.from(a.getElementsByClassName("prettyprint")).forEach(function(b){b.classList.remove("prettyprint");var c=(c=b.className.match(/\blang(?:uage)?-([\w.]+)(?!\S)/))?c[1]:void 0;c=window.prettyPrintOne(b.innerHTML,c);
c=a.V.h(c);_ds.Gd(b,c);b.getElementsByTagName("strong").length&&b.classList.add("devsite-code-highlight")})},eQ=function(a){var b=a.getElementsByTagName("pre")[0];if(b){if(b.classList.contains("devsite-disable-click-to-copy")||b.hasAttribute("no-copy")||!b.classList.contains("devsite-click-to-copy")&&!b.classList.contains("prettyprint")&&!b.classList.contains("devsite-terminal"))a.setAttribute("no-copy",""),b.classList.remove("devsite-disable-click-to-copy"),b.removeAttribute("no-copy");a.setAttribute("data-copy-event-label",
b.getAttribute("data-copy-event-label")||"");b.classList.remove("devsite-click-to-copy");b=b.getAttribute("data-label");a.K=b?"\ucf54\ub4dc \uc0d8\ud50c \ubcf5\uc0ac: "+b:"\ucf54\ub4dc \uc0d8\ud50c \ubcf5\uc0ac"}var c=a.querySelector(".devsite-enable-open-in-jsfiddle,.devsite-jsfiddle-code-sample");c&&(a.setAttribute("js-fiddle",""),c.classList.remove("devsite-enable-open-in-jsfiddle"),c.classList.add("devsite-jsfiddle-code-sample"));a.hasAttribute("js-fiddle")&&c&&["scope","jsfiddle-title","jsfiddle-wrap",
"jsfiddle-label"].forEach(function(d){c.hasAttribute("data-"+d)&&(a.setAttribute(d,c.getAttribute("data-"+d)),c.removeAttribute("data-"+d))})},fQ=function(a){var b,c;return _ds.bb(function(d){if(1==d.h){b=Array.from(a.querySelector("pre:not(.devsite-copy-hide)").childNodes);_ds.hH(document.body,b);if(!a.G)return d.H(0);c=new _ds.On;a.o.setAttribute("aria-label","\ucf54\ub4dc \uc0d8\ud50c\uc774 \ud074\ub9bd\ubcf4\ub4dc\uc5d0 \ubcf5\uc0ac\ub428");_ds.Kl(a.m,a.G,_ds.cm,function(){c.resolve()});return _ds.y(d,
c.promise,3)}_ds.Kl(a.m,a.G,_ds.cm,function(){a.o.setAttribute("aria-label",a.K)});_ds.z(d)})},gQ=function(a){a.D&&a.m.listen(a.D,"click",function(){return void a.setAttribute("dark-code","")});a.F&&a.m.listen(a.F,"click",function(){return void a.removeAttribute("dark-code")});a.o&&a.m.listen(a.o,"click",function(){return void fQ(a)});a.C&&a.m.listen(a.C,"click",function(){var b={title:a.getAttribute("jsfiddle-title")||"\ucf54\ub4dc \uc0d8\ud50c",wrap:a.getAttribute("jsfiddle-wrap")||"b",description:""},
c=a.getAttribute("scope");c?_ds.hI(c,b):_ds.gI([a],b)})};/*
 Copyright (C) 2006 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR_SHOULD_USE_CONTINUATION=!0;window.PR_TAB_WIDTH=8;window.PR_normalizedHtml=void 0;window.PR=void 0;window.prettyPrintOne=void 0;window.prettyPrint=void 0;window._pr_isIE6=function(){var a=navigator&&navigator.userAgent&&navigator.userAgent.match(/\bMSIE ([678])\./);a=a?+a[1]:!1;window._pr_isIE6=function(){return a};return a};
(function(){function a(da){return da.replace(t,"&amp;").replace(u,"&lt;").replace(v,"&gt;")}function b(da,ea,ka){switch(da.nodeType){case 1:var fa=da.tagName.toLowerCase();ea.push("<",fa);var ra=da.attributes,Ka=ra.length;if(Ka){if(ka){for(var Fa=[],ha=Ka;0<=--ha;)Fa[ha]=ra[ha];Fa.sort(function(ua,Ia){return ua.name<Ia.name?-1:ua.name===Ia.name?0:1});ra=Fa}for(ha=0;ha<Ka;++ha)Fa=ra[ha],Fa.specified&&ea.push(" ",Fa.name.toLowerCase(),'="',Fa.value.replace(t,"&amp;").replace(u,"&lt;").replace(v,"&gt;").replace(x,
"&quot;"),'"')}ea.push(">");for(ra=da.firstChild;ra;ra=ra.nextSibling)b(ra,ea,ka);!da.firstChild&&/^(?:br|link|img)$/.test(fa)||ea.push("</",fa,">");break;case 3:case 4:ea.push(a(da.nodeValue))}}function c(da){function ea(Ca){if("\\"!==Ca.charAt(0))return Ca.charCodeAt(0);switch(Ca.charAt(1)){case "b":return 8;case "t":return 9;case "n":return 10;case "v":return 11;case "f":return 12;case "r":return 13;case "u":case "x":return parseInt(Ca.substring(2),16)||Ca.charCodeAt(1);case "0":case "1":case "2":case "3":case "4":case "5":case "6":case "7":return parseInt(Ca.substring(1),
8);default:return Ca.charCodeAt(1)}}function ka(Ca){if(32>Ca)return(16>Ca?"\\x0":"\\x")+Ca.toString(16);Ca=String.fromCharCode(Ca);if("\\"===Ca||"-"===Ca||"["===Ca||"]"===Ca)Ca="\\"+Ca;return Ca}function fa(Ca){var Ga=Ca.substring(1,Ca.length-1).match(RegExp("\\\\u[0-9A-Fa-f]{4}|\\\\x[0-9A-Fa-f]{2}|\\\\[0-3][0-7]{0,2}|\\\\[0-7]{1,2}|\\\\[\\s\\S]|-|[^-\\\\]","g"));Ca=[];for(var ta=[],sa="^"===Ga[0],Aa=sa?1:0,cb=Ga.length;Aa<cb;++Aa){var Sa=Ga[Aa];switch(Sa){case "\\B":case "\\b":case "\\D":case "\\d":case "\\S":case "\\s":case "\\W":case "\\w":Ca.push(Sa);
continue}Sa=ea(Sa);if(Aa+2<cb&&"-"===Ga[Aa+1]){var nb=ea(Ga[Aa+2]);Aa+=2}else nb=Sa;ta.push([Sa,nb]);65>nb||122<Sa||(65>nb||90<Sa||ta.push([Math.max(65,Sa)|32,Math.min(nb,90)|32]),97>nb||122<Sa||ta.push([Math.max(97,Sa)&-33,Math.min(nb,122)&-33]))}ta.sort(function(Rb,Jd){return Rb[0]-Jd[0]||Jd[1]-Rb[1]});Ga=[];Sa=[NaN,NaN];for(Aa=0;Aa<ta.length;++Aa)cb=ta[Aa],cb[0]<=Sa[1]+1?Sa[1]=Math.max(Sa[1],cb[1]):Ga.push(Sa=cb);ta=["["];sa&&ta.push("^");ta.push.apply(ta,Ca);for(Aa=0;Aa<Ga.length;++Aa)cb=Ga[Aa],
ta.push(ka(cb[0])),cb[1]>cb[0]&&(cb[1]+1>cb[0]&&ta.push("-"),ta.push(ka(cb[1])));ta.push("]");return ta.join("")}function ra(Ca){for(var Ga=Ca.source.match(RegExp("(?:\\[(?:[^\\x5C\\x5D]|\\\\[\\s\\S])*\\]|\\\\u[A-Fa-f0-9]{4}|\\\\x[A-Fa-f0-9]{2}|\\\\[0-9]+|\\\\[^ux0-9]|\\(\\?[:!=]|[\\(\\)\\^]|[^\\x5B\\x5C\\(\\)\\^]+)","g")),ta=Ga.length,sa=[],Aa=0,cb=0;Aa<ta;++Aa){var Sa=Ga[Aa];"("===Sa?++cb:"\\"===Sa.charAt(0)&&(Sa=+Sa.substring(1))&&Sa<=cb&&(sa[Sa]=-1)}for(Aa=1;Aa<sa.length;++Aa)-1===sa[Aa]&&(sa[Aa]=
++Ka);for(cb=Aa=0;Aa<ta;++Aa)Sa=Ga[Aa],"("===Sa?(++cb,void 0===sa[cb]&&(Ga[Aa]="(?:")):"\\"===Sa.charAt(0)&&(Sa=+Sa.substring(1))&&Sa<=cb&&(Ga[Aa]="\\"+sa[cb]);for(cb=Aa=0;Aa<ta;++Aa)"^"===Ga[Aa]&&"^"!==Ga[Aa+1]&&(Ga[Aa]="");if(Ca.ignoreCase&&Fa)for(Aa=0;Aa<ta;++Aa)Sa=Ga[Aa],Ca=Sa.charAt(0),2<=Sa.length&&"["===Ca?Ga[Aa]=fa(Sa):"\\"!==Ca&&(Ga[Aa]=Sa.replace(/[a-zA-Z]/g,function(nb){nb=nb.charCodeAt(0);return"["+String.fromCharCode(nb&-33,nb|32)+"]"}));return Ga.join("")}for(var Ka=0,Fa=!1,ha=!1,ua=
0,Ia=da.length;ua<Ia;++ua){var V=da[ua];if(V.ignoreCase)ha=!0;else if(/[a-z]/i.test(V.source.replace(/\\u[0-9a-f]{4}|\\x[0-9a-f]{2}|\\[^ux]/gi,""))){Fa=!0;ha=!1;break}}var ab=[];ua=0;for(Ia=da.length;ua<Ia;++ua){V=da[ua];if(V.global||V.multiline)throw Error(""+V);ab.push("(?:"+ra(V)+")")}return new RegExp(ab.join("|"),ha?"gi":"g")}function d(da){var ea=0;return function(ka){for(var fa=null,ra=0,Ka=0,Fa=ka.length;Ka<Fa;++Ka)switch(ka.charAt(Ka)){case "\t":fa||(fa=[]);fa.push(ka.substring(ra,Ka));ra=
da-ea%da;for(ea+=ra;0<=ra;ra-=16)fa.push("                ".substring(0,ra));ra=Ka+1;break;case "\n":ea=0;break;default:++ea}if(!fa)return ka;fa.push(ka.substring(ra));return fa.join("")}}function e(da,ea,ka,fa){ea&&(da={source:ea,pk:da},ka(da),fa.push.apply(fa,da.Jk))}function g(da,ea){function ka(Fa){for(var ha=Fa.pk,ua=[ha,"pln"],Ia=0,V=Fa.source.match(ra)||[],ab={},Ca=0,Ga=V.length;Ca<Ga;++Ca){var ta=V[Ca],sa=ab[ta],Aa=void 0;if("string"===typeof sa)var cb=!1;else{var Sa=fa[ta.charAt(0)];if(Sa)Aa=
ta.match(Sa[1]),sa=Sa[0];else{for(cb=0;cb<Ka;++cb)if(Sa=ea[cb],Aa=ta.match(Sa[1])){sa=Sa[0];break}Aa||(sa="pln")}!(cb=5<=sa.length&&"lang-"===sa.substring(0,5))||Aa&&"string"===typeof Aa[1]||(cb=!1,sa="src");cb||(ab[ta]=sa)}Sa=Ia;Ia+=ta.length;if(cb){cb=Aa[1];var nb=ta.indexOf(cb),Rb=nb+cb.length;Aa[2]&&(Rb=ta.length-Aa[2].length,nb=Rb-cb.length);sa=sa.substring(5);e(ha+Sa,ta.substring(0,nb),ka,ua);e(ha+Sa+nb,cb,m(sa,cb),ua);e(ha+Sa+Rb,ta.substring(Rb),ka,ua)}else ua.push(ha+Sa,sa)}Fa.Jk=ua}var fa=
{},ra;(function(){for(var Fa=da.concat(ea),ha=[],ua={},Ia=0,V=Fa.length;Ia<V;++Ia){var ab=Fa[Ia],Ca=ab[3];if(Ca)for(var Ga=Ca.length;0<=--Ga;)fa[Ca.charAt(Ga)]=ab;ab=ab[1];Ca=""+ab;ua.hasOwnProperty(Ca)||(ha.push(ab),ua[Ca]=null)}ha.push(/[\0-\uffff]/);ra=c(ha)})();var Ka=ea.length;return ka}function h(da){var ea=[],ka=[];da.tripleQuotedStrings?ea.push(["str",/^(?:'''(?:[^'\\]|\\[\s\S]|'{1,2}(?=[^']))*(?:'''|$)|"""(?:[^"\\]|\\[\s\S]|"{1,2}(?=[^"]))*(?:"""|$)|'(?:[^\\']|\\[\s\S])*(?:'|$)|"(?:[^\\"]|\\[\s\S])*(?:"|$))/,
null,"'\""]):da.multiLineStrings?ea.push(["str",/^(?:'(?:[^\\']|\\[\s\S])*(?:'|$)|"(?:[^\\"]|\\[\s\S])*(?:"|$)|`(?:[^\\`]|\\[\s\S])*(?:`|$))/,null,"'\"`"]):ea.push(["str",/^(?:'(?:[^\\'\r\n]|\\.)*(?:'|$)|"(?:[^\\"\r\n]|\\.)*(?:"|$))/,null,"\"'"]);da.verbatimStrings&&ka.push(["str",/^@"(?:[^"]|"")*(?:"|$)/,null]);var fa=da.hashComments;fa&&(da.cStyleComments?(1<fa?ea.push(["com",/^#(?:##(?:[^#]|#(?!##))*(?:###|$)|.*)/,null,"#"]):ea.push(["com",/^#(?:(?:define|elif|else|endif|error|ifdef|include|ifndef|line|pragma|undef|warning)\b|[^\r\n]*)/,
null,"#"]),ka.push(["str",/^<(?:(?:(?:\.\.\/)*|\/?)(?:[\w-]+(?:\/[\w-]+)+)?[\w-]+\.h|[a-z]\w*)>/,null])):ea.push(["com",/^#[^\r\n]*/,null,"#"]));da.cStyleComments&&(ka.push(["com",/^\/\/[^\r\n]*/,null]),ka.push(["com",/^\/\*[\s\S]*?(?:\*\/|$)/,null]));da.regexLiterals&&ka.push(["lang-regex",new RegExp("^"+q+"(/(?=[^/*])(?:[^/\\x5B\\x5C]|\\x5C[\\s\\S]|\\x5B(?:[^\\x5C\\x5D]|\\x5C[\\s\\S])*(?:\\x5D|$))+/)")]);da=da.keywords.replace(/^\s+|\s+$/g,"");da.length&&ka.push(["kwd",new RegExp("^(?:"+da.replace(/\s+/g,
"|")+")\\b"),null]);ea.push(["pln",/^\s+/,null," \r\n\t\u00a0"]);ka.push(["lit",/^@[a-z_$][a-z_$@0-9]*/i,null],["typ",/^@?[A-Z]+[a-z][A-Za-z_$@0-9]*/,null],["pln",/^[a-z_$][a-z_$@0-9]*/i,null],["lit",RegExp("^(?:0x[a-f0-9]+|(?:\\d(?:_\\d+)*\\d*(?:\\.\\d*)?|\\.\\d\\+)(?:e[+\\-]?\\d+)?)[a-z]*","i"),null,"0123456789"],["pun",/^.[^\s\w\.$@'"`\/#]*/,null]);return g(ea,ka)}function k(da){function ea(ue){if(ue>ua){Ia&&Ia!==V&&(ha.push("</span>"),Ia=null);!Ia&&V&&(Ia=V,ha.push('<span class="',Ia,'">'));var bf=
a(Ga(ka.substring(ua,ue))).replace(Sa?sa:ta,"$1&#160;");Sa=cb.test(bf);ha.push(bf.replace(Aa,af));ua=ue}}var ka=da.source,fa=da.Op,ra=da.Jk,Ka=da.Ll,Fa=da.Im,ha=[],ua=0,Ia=null,V=null,ab=0,Ca=0,Ga=d(window.PR_TAB_WIDTH),ta=/([\r\n ]) /g,sa=/(^| ) /gm,Aa=/\r\n?|\n/g,cb=/[ \r\n]$/,Sa=!0,nb=window._pr_isIE6();Fa=nb?Fa&&"PRE"===Fa.tagName?6===nb?"&#160;\r\n":7===nb?"&#160;<br />\r":8===nb?"&#160;<br />":"&#160;\r":"&#160;<br />":"<br />";if(Ka){var Rb=[];for(nb=0;10>nb;++nb)Rb[nb]=Fa+'</li><li class="L'+
nb+'">';var Jd="number"===typeof Ka?Ka-1:0;ha.push('<ol class="linenums"><li class="L',Jd%10,'"');Jd&&ha.push(' value="',Jd+1,'"');ha.push(">");var af=function(){var ue=Rb[++Jd%10];return Ia?"</span>"+ue+'<span class="'+Ia+'">':ue}}else af=Fa;for(;;)if(ab<fa.length&&(Ca<ra.length?fa[ab]<=ra[Ca]:1))ea(fa[ab]),Ia&&(ha.push("</span>"),Ia=null),ha.push(fa[ab+1]),ab+=2;else if(Ca<ra.length)ea(ra[Ca]),V=ra[Ca+1],Ca+=2;else break;ea(ka.length);Ia&&ha.push("</span>");Ka&&ha.push("</li></ol>");da.zi=ha.join("")}
function l(da,ea){for(var ka=ea.length;0<=--ka;){var fa=ea[ka];Ua.hasOwnProperty(fa)?"console"in window&&console.warn("cannot override language handler %s",fa):Ua[fa]=da}}function m(da,ea){da&&Ua.hasOwnProperty(da)||(da=/^\s*</.test(ea)?"default-markup":"default-code");return Ua[da]}function p(da){var ea=da.Hm,ka=da.Cl;da.zi=ea;try{var fa=ea.match(oa);ea=[];var ra=0,Ka=[];if(fa)for(var Fa=0,ha=fa.length;Fa<ha;++Fa){var ua=fa[Fa];if(1<ua.length&&"<"===ua.charAt(0)){if(!ba.test(ua))if(Ea.test(ua))ea.push(ua.substring(9,
ua.length-3)),ra+=ua.length-12;else if(Za.test(ua))ea.push("\n"),++ra;else if(0<=ua.indexOf("nocode")&&ua.replace(/\s(\w+)\s*=\s*(?:"([^"]*)"|'([^']*)'|(\S+))/g,' $1="$2$3$4"').match(/[cC][lL][aA][sS][sS]="[^"]*\bnocode\b/)){var Ia=ua.match(Da)[2],V=1;var ab=Fa+1;a:for(;ab<ha;++ab){var Ca=fa[ab].match(Da);if(Ca&&Ca[2]===Ia)if("/"===Ca[1]){if(0===--V)break a}else++V}ab<ha?(Ka.push(ra,fa.slice(Fa,ab+1).join("")),Fa=ab):Ka.push(ra,ua)}else Ka.push(ra,ua)}else{V=ua;var Ga=V.indexOf("&");if(0>Ga)var ta=
V;else{for(--Ga;0<=(Ga=V.indexOf("&#",Ga+1));){var sa=V.indexOf(";",Ga);if(0<=sa){var Aa=V.substring(Ga+3,sa),cb=10;Aa&&"x"===Aa.charAt(0)&&(Aa=Aa.substring(1),cb=16);var Sa=parseInt(Aa,cb);isNaN(Sa)||(V=V.substring(0,Ga)+String.fromCharCode(Sa)+V.substring(sa+1))}}ta=V.replace(G,"<").replace(H,">").replace(M,"'").replace(W,'"').replace(ca," ").replace(S,"&")}ea.push(ta);ra+=ta.length}}var nb=ea.join("");da.source=nb;da.pk=0;da.Op=Ka;m(ka,nb)(da);k(da)}catch(Rb){"console"in window&&console.log(Rb&&
Rb.stack?Rb.stack:Rb)}}var q=function(){for(var da="! != !== # % %= & && &&= &= ( * *= += , -= -> / /= : :: ; < << <<= <= = == === > >= >> >>= >>> >>>= ? @ [ ^ ^= ^^ ^^= { | |= || ||= ~ break case continue delete do else finally instanceof return throw try typeof".split(" "),ea="(?:^^|[+-]",ka=0;ka<da.length;++ka)ea+="|"+da[ka].replace(/([^=<>:&a-z])/g,"\\$1");return ea+")\\s*"}(),t=/&/g,u=/</g,v=/>/g,x=/"/g,G=/&lt;/g,H=/&gt;/g,M=/&apos;/g,W=/&quot;/g,S=/&amp;/g,ca=/&nbsp;/g,ia=/[\r\n]/g,aa=null,
oa=RegExp("[^<]+|\x3c!--[\\s\\S]*?--\x3e|<!\\[CDATA\\[[\\s\\S]*?\\]\\]>|</?[a-zA-Z](?:[^>\"']|'[^']*'|\"[^\"]*\")*>|<","g"),ba=/^\x3c!--/,Ea=/^<!\[CDATA\[/,Za=/^<br\b/i,Da=/^<(\/?)([a-zA-Z][a-zA-Z0-9]*)/,Qa=h({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof alignof align_union asm axiom bool concept concept_map const_cast constexpr decltype dynamic_cast explicit export friend inline late_check mutable namespace nullptr reinterpret_cast static_assert static_cast template typeid typename using virtual wchar_t where break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient as base by checked decimal delegate descending dynamic event fixed foreach from group implicit in interface internal into is lock object out override orderby params partial readonly ref sbyte sealed stackalloc string select uint ulong unchecked unsafe ushort var break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof debugger eval export function get null set undefined var with Infinity NaN caller delete die do dump elsif eval exit foreach for goto if import last local my next no our print package redo require sub undef unless until use wantarray while BEGIN END break continue do else for if return while and as assert class def del elif except exec finally from global import in is lambda nonlocal not or pass print raise try with yield False True None break continue do else for if return while alias and begin case class def defined elsif end ensure false in module next nil not or redo rescue retry self super then true undef unless until when yield BEGIN END break continue do else for if return while case done elif esac eval fi function in local set then until ",
hashComments:!0,cStyleComments:!0,multiLineStrings:!0,regexLiterals:!0}),Ua={};l(Qa,["default-code"]);l(g([],[["pln",/^[^<?]+/],["dec",/^<!\w[^>]*(?:>|$)/],["com",/^\x3c!--[\s\S]*?(?:-\->|$)/],["lang-",/^<\?([\s\S]+?)(?:\?>|$)/],["lang-",/^<%([\s\S]+?)(?:%>|$)/],["pun",/^(?:<[%?]|[%?]>)/],["lang-",/^<xmp\b[^>]*>([\s\S]+?)<\/xmp\b[^>]*>/i],["lang-js",/^<script\b[^>]*>([\s\S]*?)(<\/script\b[^>]*>)/i],["lang-css",/^<style\b[^>]*>([\s\S]*?)(<\/style\b[^>]*>)/i],["lang-in.tag",/^(<\/?[a-z][^<>]*>)/i]]),
"default-markup htm html mxml xhtml xml xsl".split(" "));l(g([["pln",/^[\s]+/,null," \t\r\n"],["atv",/^(?:"[^"]*"?|'[^']*'?)/,null,"\"'"]],[["tag",/^^<\/?[a-z](?:[\w.:-]*\w)?|\/?>$/i],["atn",/^(?!style[\s=]|on)[a-z](?:[\w:-]*\w)?/i],["lang-uq.val",/^=\s*([^>'"\s]*(?:[^>'"\s\/]|\/(?=\s)))/],["pun",/^[=<>\/]+/],["lang-js",/^on\w+\s*=\s*"([^"]+)"/i],["lang-js",/^on\w+\s*=\s*'([^']+)'/i],["lang-js",/^on\w+\s*=\s*([^"'>\s]+)/i],["lang-css",/^style\s*=\s*"([^"]+)"/i],["lang-css",/^style\s*=\s*'([^']+)'/i],
["lang-css",/^style\s*=\s*([^"'>\s]+)/i]]),["in.tag"]);l(g([],[["atv",/^[\s\S]+/]]),["uq.val"]);l(h({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof alignof align_union asm axiom bool concept concept_map const_cast constexpr decltype dynamic_cast explicit export friend inline late_check mutable namespace nullptr reinterpret_cast static_assert static_cast template typeid typename using virtual wchar_t where ",
hashComments:!0,cStyleComments:!0}),"c cc cpp cxx cyc m".split(" "));l(h({keywords:"null true false"}),["json"]);l(h({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient as base by checked decimal delegate descending dynamic event fixed foreach from group implicit in interface internal into is lock object out override orderby params partial readonly ref sbyte sealed stackalloc string select uint ulong unchecked unsafe ushort var ",
hashComments:!0,cStyleComments:!0,verbatimStrings:!0}),["cs"]);l(h({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient ",
cStyleComments:!0}),["java"]);l(h({keywords:"break continue do else for if return while case done elif esac eval fi function in local set then until ",hashComments:!0,multiLineStrings:!0}),["bsh","csh","sh"]);l(h({keywords:"break continue do else for if return while and as assert class def del elif except exec finally from global import in is lambda nonlocal not or pass print raise try with yield False True None ",hashComments:!0,multiLineStrings:!0,tripleQuotedStrings:!0}),["cv","py"]);l(h({keywords:"caller delete die do dump elsif eval exit foreach for goto if import last local my next no our print package redo require sub undef unless until use wantarray while BEGIN END ",
hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["perl","pl","pm"]);l(h({keywords:"break continue do else for if return while alias and begin case class def defined elsif end ensure false in module next nil not or redo rescue retry self super then true undef unless until when yield BEGIN END ",hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["rb"]);l(h({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof debugger eval export function get null set undefined var with Infinity NaN ",
cStyleComments:!0,regexLiterals:!0}),["js"]);l(h({keywords:"all and by catch class else extends false finally for if in is isnt loop new no not null of off on or return super then true try unless until when while yes ",hashComments:3,cStyleComments:!0,multilineStrings:!0,tripleQuotedStrings:!0,regexLiterals:!0}),["coffee"]);l(g([],[["str",/^[\s\S]+/]]),["regex"]);window.PR_normalizedHtml=b;window.prettyPrintOne=function(da,ea,ka){da={Hm:da,Cl:ea,Ll:ka};p(da);return da.zi};window.prettyPrint=function(da){function ea(){for(var V=
window.PR_SHOULD_USE_CONTINUATION?ha.now()+250:Infinity;ua<fa.length&&ha.now()<V;ua++){var ab=fa[ua];if(ab.className&&0<=ab.className.indexOf("prettyprint")){var Ca=ab.className.match(/\blang-(\w+)\b/);Ca&&(Ca=Ca[1]);for(var Ga=!1,ta=ab.parentNode;ta;ta=ta.parentNode)if(("pre"===ta.tagName||"code"===ta.tagName||"xmp"===ta.tagName)&&ta.className&&0<=ta.className.indexOf("prettyprint")){Ga=!0;break}if(!Ga){ta=ab;null===aa&&(Ga=document.createElement("PRE"),Ga.appendChild(document.createTextNode('<!DOCTYPE foo PUBLIC "foo bar">\n<foo />')),
aa=!/</.test(Ga.innerHTML));if(aa)if(Ga=ta.innerHTML,"XMP"===ta.tagName)Ga=a(Ga);else{if("PRE"!==ta.tagName&&ia.test(Ga)){var sa="";ta.currentStyle?sa=ta.currentStyle.whiteSpace:window.getComputedStyle&&(sa=window.getComputedStyle(ta,null).whiteSpace);ta=!sa||"pre"===sa}else ta=!0;ta||(Ga=Ga.replace(/(<br\s*\/?>)[\r\n]+/g,"$1").replace(/(?:[\r\n]+[ \t]*)+/g," "))}else{Ga=[];for(ta=ta.firstChild;ta;ta=ta.nextSibling)b(ta,Ga);Ga=Ga.join("")}Ga=Ga.replace(/(?:\r\n?|\n)$/,"");ta=ab.className.match(/\blinenums\b(?::(\d+))?/);
Ia={Hm:Ga,Cl:Ca,Im:ab,Ll:ta?ta[1]&&ta[1].length?+ta[1]:!0:!1};p(Ia);if(ab=Ia.zi)if(Ca=Ia.Im,"XMP"===Ca.tagName){Ga=document.createElement("PRE");for(ta=0;ta<Ca.attributes.length;++ta)sa=Ca.attributes[ta],sa.specified&&("class"===sa.name.toLowerCase()?Ga.className=sa.value:Ga.setAttribute(sa.name,sa.value));Ga.innerHTML=ab;Ca.parentNode.replaceChild(Ga,Ca)}else Ca.innerHTML=ab}}}ua<fa.length?setTimeout(ea,250):da&&da()}for(var ka=[document.getElementsByTagName("pre"),document.getElementsByTagName("code"),
document.getElementsByTagName("xmp")],fa=[],ra=0;ra<ka.length;++ra)for(var Ka=0,Fa=ka[ra].length;Ka<Fa;++Ka)fa.push(ka[ra][Ka]);ka=null;var ha=Date;ha.now||(ha={now:function(){return(new Date).getTime()}});var ua=0,Ia;ea()};window.PR={combinePrefixPatterns:c,createSimpleLexer:g,registerLangHandler:l,sourceDecorator:h,PR_ATTRIB_NAME:"atn",PR_ATTRIB_VALUE:"atv",PR_COMMENT:"com",PR_DECLARATION:"dec",PR_KEYWORD:"kwd",PR_LITERAL:"lit",PR_NOCODE:"nocode",PR_PLAIN:"pln",PR_PUNCTUATION:"pun",PR_SOURCE:"src",
PR_STRING:"str",PR_TAG:"tag",PR_TYPE:"typ"}})();/*
 Copyright (C) 2009 Onno Hommes.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_COMMENT,/^#[^\r\n]*/,null,"#"],[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[PR.PR_KEYWORD,/^(?:ADS|AD|AUG|BZF|BZMF|CAE|CAF|CA|CCS|COM|CS|DAS|DCA|DCOM|DCS|DDOUBL|DIM|DOUBLE|DTCB|DTCF|DV|DXCH|EDRUPT|EXTEND|INCR|INDEX|NDX|INHINT|LXCH|MASK|MSK|MP|MSU|NOOP|OVSK|QXCH|RAND|READ|RELINT|RESUME|RETURN|ROR|RXOR|SQUARE|SU|TCR|TCAA|OVSK|TCF|TC|TS|WAND|WOR|WRITE|XCH|XLQ|XXALQ|ZL|ZQ|ADD|ADZ|SUB|SUZ|MPY|MPR|MPZ|DVP|COM|ABS|CLA|CLZ|LDQ|STO|STQ|ALS|LLS|LRS|TRA|TSQ|TMI|TOV|AXT|TIX|DLY|INP|OUT)\s/,
null],[PR.PR_TYPE,/^(?:-?GENADR|=MINUS|2BCADR|VN|BOF|MM|-?2CADR|-?[1-6]DNADR|ADRES|BBCON|[SE]?BANK=?|BLOCK|BNKSUM|E?CADR|COUNT\*?|2?DEC\*?|-?DNCHAN|-?DNPTR|EQUALS|ERASE|MEMORY|2?OCT|REMADR|SETLOC|SUBRO|ORG|BSS|BES|SYN|EQU|DEFINE|END)\s/,null],[PR.PR_LITERAL,/^'(?:-*(?:\w|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?)?/],[PR.PR_PLAIN,/^-*(?:[!-z_]|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0()"\\';]+/]]),["apollo","agc","aea"]);/*
 Copyright (C) 2011 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([["opn",/^[\(\{\[]+/,null,"([{"],["clo",/^[\)\}\]]+/,null,")]}"],[PR.PR_COMMENT,/^;[^\r\n]*/,null,";"],[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[PR.PR_KEYWORD,/^(?:def|if|do|let|quote|var|fn|loop|recur|throw|try|monitor-enter|monitor-exit|defmacro|defn|defn-|macroexpand|macroexpand-1|for|doseq|dosync|dotimes|and|or|when|not|assert|doto|proxy|defstruct|first|rest|cons|defprotocol|deftype|defrecord|reify|defmulti|defmethod|meta|with-meta|ns|in-ns|create-ns|import|intern|refer|alias|namespace|resolve|ref|deref|refset|new|set!|memfn|to-array|into-array|aset|gen-class|reduce|map|filter|find|nil?|empty?|hash-map|hash-set|vec|vector|seq|flatten|reverse|assoc|dissoc|list|list?|disj|get|union|difference|intersection|extend|extend-type|extend-protocol|prn)\b/,
null],[PR.PR_TYPE,/^:[0-9a-zA-Z\-]+/]]),["clj"]);/*
 Copyright (C) 2009 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[ \t\r\n\f]+/,null," \t\r\n\f"]],[[PR.PR_STRING,/^"(?:[^\n\r\f\\"]|\\(?:\r\n?|\n|\f)|\\[\s\S])*"/,null],[PR.PR_STRING,/^'(?:[^\n\r\f\\']|\\(?:\r\n?|\n|\f)|\\[\s\S])*'/,null],["lang-css-str",/^url\(([^\)"']*)\)/i],[PR.PR_KEYWORD,/^(?:url|rgb|!important|@import|@page|@media|@charset|inherit)(?=[^\-\w]|$)/i,null],["lang-css-kw",/^(-?(?:[_a-z]|(?:\\[0-9a-f]+ ?))(?:[_a-z0-9\-]|\\(?:\\[0-9a-f]+ ?))*)\s*:/i],[PR.PR_COMMENT,/^\/\*[^*]*\*+(?:[^\/*][^*]*\*+)*\//],
[PR.PR_COMMENT,/^(?:\x3c!--|--\x3e)/],[PR.PR_LITERAL,/^(?:\d+|\d*\.\d+)(?:%|[a-z]+)?/i],[PR.PR_LITERAL,/^#(?:[0-9a-f]{3}){1,2}/i],[PR.PR_PLAIN,/^-?(?:[_a-z]|(?:\\[\da-f]+ ?))(?:[_a-z\d\-]|\\(?:\\[\da-f]+ ?))*/i],[PR.PR_PUNCTUATION,/^[^\s\w'"]+/]]),["css"]);PR.registerLangHandler(PR.createSimpleLexer([],[[PR.PR_KEYWORD,/^-?(?:[_a-z]|(?:\\[\da-f]+ ?))(?:[_a-z\d\-]|\\(?:\\[\da-f]+ ?))*/i]]),["css-kw"]);PR.registerLangHandler(PR.createSimpleLexer([],[[PR.PR_STRING,/^[^\)"']+/]]),["css-str"]);/*
 Copyright (C) 2010 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_PLAIN,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])+(?:'|$))/,null,"\"'"]],[[PR.PR_COMMENT,/^(?:\/\/[^\r\n]*|\/\*[\s\S]*?\*\/)/],[PR.PR_PLAIN,/^(?:[^\/"']|\/(?![\/\*]))+/i]]),["go"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\x0B\x0C\r ]+/,null,"\t\n\x0B\f\r "],[PR.PR_STRING,/^"(?:[^"\\\n\x0C\r]|\\[\s\S])*(?:"|$)/,null,'"'],[PR.PR_STRING,/^'(?:[^'\\\n\x0C\r]|\\[^&])'?/,null,"'"],[PR.PR_LITERAL,/^(?:0o[0-7]+|0x[\da-f]+|\d+(?:\.\d+)?(?:e[+\-]?\d+)?)/i,null,"0123456789"]],[[PR.PR_COMMENT,/^(?:(?:--+(?:[^\r\n\x0C]*)?)|(?:\{-(?:[^-]|-+[^-\}])*-\}))/],[PR.PR_KEYWORD,/^(?:case|class|data|default|deriving|do|else|if|import|in|infix|infixl|infixr|instance|let|module|newtype|of|then|type|where|_)(?=[^a-zA-Z0-9']|$)/,
null],[PR.PR_PLAIN,/^(?:[A-Z][\w']*\.)*[a-zA-Z][\w']*/],[PR.PR_PUNCTUATION,/^[^\t\n\x0B\x0C\r a-zA-Z0-9'"]+/]]),["hs"]);/*

 Copyright (C) 2017 Micha? B?czkowski

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_PUNCTUATION,/^[.!%&()*+,\-;<=>?\[\\\]^{|}:]+/,null,".!%&()*+,-;<=>?[\\]^{|}:"]],[[PR.PR_KEYWORD,/^\b(package|public|protected|private|open|abstract|constructor|final|override|import|for|while|as|typealias|get|set|((data|enum|annotation|sealed) )?class|this|super|val|var|fun|is|in|throw|return|break|continue|(companion )?object|if|try|else|do|when|init|interface|typeof|suspend)\b/],[PR.PR_LITERAL,
/^(?:true|false|null)\b/],[PR.PR_LITERAL,/^(0[xX][0-9a-fA-F_]+L?|0[bB][0-1]+L?|[0-9_.]+([eE]-?[0-9]+)?[fFL]?)/],[PR.PR_TYPE,/^(\b[A-Z]+[a-z][a-zA-Z0-9_$@]*|`.*`)/,null],[PR.PR_COMMENT,/^\/\/.*/],[PR.PR_COMMENT,/^\/\*[\s\S]*?(?:\*\/|$)/],[PR.PR_STRING,/'.'/],[PR.PR_STRING,/^"([^"\\]|\\[\s\S])*"/],[PR.PR_STRING,/^"{3}[\s\S]*?[^\\]"{3}/],[PR.PR_LITERAL,/^@([a-zA-Z0-9_$@]*|`.*`)/],[PR.PR_LITERAL,/^[a-zA-Z0-9_]+@/]]),["kotlin"]);/*
 Copyright (C) 2008 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([["opn",/^\(+/,null,"("],["clo",/^\)+/,null,")"],[PR.PR_COMMENT,/^;[^\r\n]*/,null,";"],[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[PR.PR_KEYWORD,/^(?:block|c[ad]+r|catch|con[ds]|def(?:ine|un)|do|eq|eql|equal|equalp|eval-when|flet|format|go|if|labels|lambda|let|load-time-value|locally|macrolet|multiple-value-call|nil|progn|progv|quote|require|return-from|setq|symbol-macrolet|t|tagbody|the|throw|unwind)\b/,
null],[PR.PR_LITERAL,/^[+\-]?(?:[0#]x[0-9a-f]+|\d+\/\d+|(?:\.\d+|\d+(?:\.\d*)?)(?:[ed][+\-]?\d+)?)/i],[PR.PR_LITERAL,/^'(?:-*(?:\w|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?)?/],[PR.PR_PLAIN,/^-*(?:[a-z_]|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0()"\\';]+/]]),["cl","el","lisp","scm"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])*(?:'|$))/,null,"\"'"]],[[PR.PR_COMMENT,/^--(?:\[(=*)\[[\s\S]*?(?:\]\1\]|$)|[^\r\n]*)/],[PR.PR_STRING,/^\[(=*)\[[\s\S]*?(?:\]\1\]|$)/],[PR.PR_KEYWORD,/^(?:and|break|do|else|elseif|end|false|for|function|if|in|local|nil|not|or|repeat|return|then|true|until|while)\b/,null],[PR.PR_LITERAL,/^[+-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],
[PR.PR_PLAIN,/^[a-z_]\w*/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0][^\w\t\n\r \xA0"'\-\+=]*/]]),["lua"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_COMMENT,/^#(?:if[\t\n\r \xA0]+(?:[a-z_$][\w']*|``[^\r\n\t`]*(?:``|$))|else|endif|light)/i,null,"#"],[PR.PR_STRING,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])(?:'|$))/,null,"\"'"]],[[PR.PR_COMMENT,/^(?:\/\/[^\r\n]*|\(\*[\s\S]*?\*\))/],[PR.PR_KEYWORD,/^(?:abstract|and|as|assert|begin|class|default|delegate|do|done|downcast|downto|elif|else|end|exception|extern|false|finally|for|fun|function|if|in|inherit|inline|interface|internal|lazy|let|match|member|module|mutable|namespace|new|null|of|open|or|override|private|public|rec|return|static|struct|then|to|true|try|type|upcast|use|val|void|when|while|with|yield|asr|land|lor|lsl|lsr|lxor|mod|sig|atomic|break|checked|component|const|constraint|constructor|continue|eager|event|external|fixed|functor|global|include|method|mixin|object|parallel|process|protected|pure|sealed|trait|virtual|volatile)\b/],
[PR.PR_LITERAL,/^[+\-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],[PR.PR_PLAIN,/^(?:[a-z_][\w']*[!?#]?|``[^\r\n\t`]*(?:``|$))/i],[PR.PR_PUNCTUATION,/^[^\t\n\r \xA0"'\w]+/]]),["fs","ml"]);PR.registerLangHandler(PR.sourceDecorator({keywords:"bool bytes default double enum extend extensions false fixed32 fixed64 float group import int32 int64 max message option optional package repeated required returns rpc service sfixed32 sfixed64 sint32 sint64 string syntax to true uint32 uint64",cStyleComments:!0}),["proto"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^(?:"(?:(?:""(?:""?(?!")|[^\\"]|\\.)*"{0,3})|(?:[^"\r\n\\]|\\.)*"?))/,null,'"'],[PR.PR_LITERAL,/^`(?:[^\r\n\\`]|\\.)*`?/,null,"`"],[PR.PR_PUNCTUATION,/^[!#%&()*+,\-:;<=>?@\[\\\]^{|}~]+/,null,"!#%&()*+,-:;<=>?@[\\]^{|}~"]],[[PR.PR_STRING,/^'(?:[^\r\n\\']|\\(?:'|[^\r\n']+))'/],[PR.PR_LITERAL,/^'[a-zA-Z_$][\w$]*(?!['$\w])/],[PR.PR_KEYWORD,/^(?:abstract|case|catch|class|def|do|else|extends|final|finally|for|forSome|if|implicit|import|lazy|match|new|object|override|package|private|protected|requires|return|sealed|super|throw|trait|try|type|val|var|while|with|yield)\b/],
[PR.PR_LITERAL,/^(?:true|false|null|this)\b/],[PR.PR_LITERAL,/^(?:(?:0(?:[0-7]+|X[0-9A-F]+))L?|(?:(?:0|[1-9][0-9]*)(?:(?:\.[0-9]+)?(?:E[+\-]?[0-9]+)?F?|L?))|\\.[0-9]+(?:E[+\-]?[0-9]+)?F?)/i],[PR.PR_TYPE,/^[$_]*[A-Z][_$A-Z0-9]*[a-z][\w$]*/],[PR.PR_PLAIN,/^[$a-zA-Z_][\w$]*/],[PR.PR_COMMENT,/^\/(?:\/.*|\*(?:\/|\**[^*/])*(?:\*+\/?)?)/],[PR.PR_PUNCTUATION,/^(?:\.+|\/)/]]),["scala"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^(?:"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*')/,null,"\"'"]],[[PR.PR_COMMENT,/^(?:--[^\r\n]*|\/\*[\s\S]*?(?:\*\/|$))/],[PR.PR_KEYWORD,/^(?:ADD|ALL|ALTER|AND|ANY|AS|ASC|AUTHORIZATION|BACKUP|BEGIN|BETWEEN|BREAK|BROWSE|BULK|BY|CASCADE|CASE|CHECK|CHECKPOINT|CLOSE|CLUSTERED|COALESCE|COLLATE|COLUMN|COMMIT|COMPUTE|CONSTRAINT|CONTAINS|CONTAINSTABLE|CONTINUE|CONVERT|CREATE|CROSS|CURRENT|CURRENT_DATE|CURRENT_TIME|CURRENT_TIMESTAMP|CURRENT_USER|CURSOR|DATABASE|DBCC|DEALLOCATE|DECLARE|DEFAULT|DELETE|DENY|DESC|DISK|DISTINCT|DISTRIBUTED|DOUBLE|DROP|DUMMY|DUMP|ELSE|END|ERRLVL|ESCAPE|EXCEPT|EXEC|EXECUTE|EXISTS|EXIT|FETCH|FILE|FILLFACTOR|FOR|FOREIGN|FREETEXT|FREETEXTTABLE|FROM|FULL|FUNCTION|GOTO|GRANT|GROUP|HAVING|HOLDLOCK|IDENTITY|IDENTITYCOL|IDENTITY_INSERT|IF|IN|INDEX|INNER|INSERT|INTERSECT|INTO|IS|JOIN|KEY|KILL|LEFT|LIKE|LINENO|LOAD|NATIONAL|NOCHECK|NONCLUSTERED|NOT|NULL|NULLIF|OF|OFF|OFFSETS|ON|OPEN|OPENDATASOURCE|OPENQUERY|OPENROWSET|OPENXML|OPTION|OR|ORDER|OUTER|OVER|PERCENT|PLAN|PRECISION|PRIMARY|PRINT|PROC|PROCEDURE|PUBLIC|RAISERROR|READ|READTEXT|RECONFIGURE|REFERENCES|REPLICATION|RESTORE|RESTRICT|RETURN|REVOKE|RIGHT|ROLLBACK|ROWCOUNT|ROWGUIDCOL|RULE|SAVE|SCHEMA|SELECT|SESSION_USER|SET|SETUSER|SHUTDOWN|SOME|STATISTICS|SYSTEM_USER|TABLE|TEXTSIZE|THEN|TO|TOP|TRAN|TRANSACTION|TRIGGER|TRUNCATE|TSEQUAL|UNION|UNIQUE|UPDATE|UPDATETEXT|USE|USER|VALUES|VARYING|VIEW|WAITFOR|WHEN|WHERE|WHILE|WITH|WRITETEXT)(?=[^\w-]|$)/i,
null],[PR.PR_LITERAL,/^[+-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],[PR.PR_PLAIN,/^[a-z_][\w-]*/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0"'][^\w\t\n\r \xA0+\-"']*/]]),["sql"]);/*
 Copyright (C) 2015 Google Inc.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[ \n\r\t\v\f\0]+/,null," \n\r\t\v\f\x00"],[PR.PR_STRING,/^"(?:[^"\\]|(?:\\.)|(?:\\\((?:[^"\\)]|\\.)*\)))*"/,null,'"']],[[PR.PR_LITERAL,/^(?:(?:0x[\da-fA-F][\da-fA-F_]*\.[\da-fA-F][\da-fA-F_]*[pP]?)|(?:\d[\d_]*\.\d[\d_]*[eE]?))[+-]?\d[\d_]*/,null],[PR.PR_LITERAL,/^-?(?:(?:0(?:(?:b[01][01_]*)|(?:o[0-7][0-7_]*)|(?:x[\da-fA-F][\da-fA-F_]*)))|(?:\d[\d_]*))/,null],[PR.PR_LITERAL,/^(?:true|false|nil)\b/,null],[PR.PR_KEYWORD,/^\b(?:__COLUMN__|__FILE__|__FUNCTION__|__LINE__|associativity|as|break|case|class|continue|convenience|default|deinit|didSet|do|dynamic|dynamicType|else|enum|fallthrough|final|for|func|get|import|infix|init|inout|internal|if|in|is|lazy|left|let|mutating|none|nonmutating|operator|optional|override|postfix|precedence|prefix|private|protocol|Protocol|public|required|return|right|safe|self|set|static|struct|subscript|super|switch|Type|typealias|unowned|unsafe|var|weak|while|willSet)\b/,
null],[PR.PR_COMMENT,/^\/\/.*?[\n\r]/,null],[PR.PR_COMMENT,/^\/\*[\s\S]*?(?:\*\/|$)/,null],[PR.PR_PUNCTUATION,/^<<=|<=|<<|>>=|>=|>>|===|==|\.\.\.|&&=|\.\.<|!==|!=|&=|~=|~|\(|\)|\[|\]|{|}|@|#|;|\.|,|:|\|\|=|\?\?|\|\||&&|&\*|&\+|&-|&=|\+=|-=|\/=|\*=|\^=|%=|\|=|->|`|==|\+\+|--|\/|\+|!|\*|%|<|>|&|\||\^|\?|=|-|_/,null],[PR.PR_TYPE,/^\b(?:[@_]?[A-Z]+[a-z][A-Za-z_$@0-9]*|\w+_t\b)/,null]]),["swift"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0\u2028\u2029]+/,null,"\t\n\r \u00a0\u2028\u2029"],[PR.PR_STRING,/^(?:["\u201C\u201D](?:[^"\u201C\u201D]|["\u201C\u201D]{2})(?:["\u201C\u201D]c|$)|["\u201C\u201D](?:[^"\u201C\u201D]|["\u201C\u201D]{2})*(?:["\u201C\u201D]|$))/i,null,'"\u201c\u201d'],[PR.PR_COMMENT,/^['\u2018\u2019][^\r\n\u2028\u2029]*/,null,"'\u2018\u2019"]],[[PR.PR_KEYWORD,/^(?:AddHandler|AddressOf|Alias|And|AndAlso|Ansi|As|Assembly|Auto|Boolean|ByRef|Byte|ByVal|Call|Case|Catch|CBool|CByte|CChar|CDate|CDbl|CDec|Char|CInt|Class|CLng|CObj|Const|CShort|CSng|CStr|CType|Date|Decimal|Declare|Default|Delegate|Dim|DirectCast|Do|Double|Each|Else|ElseIf|End|EndIf|Enum|Erase|Error|Event|Exit|Finally|For|Friend|Function|Get|GetType|GoSub|GoTo|Handles|If|Implements|Imports|In|Inherits|Integer|Interface|Is|Let|Lib|Like|Long|Loop|Me|Mod|Module|MustInherit|MustOverride|MyBase|MyClass|Namespace|New|Next|Not|NotInheritable|NotOverridable|Object|On|Option|Optional|Or|OrElse|Overloads|Overridable|Overrides|ParamArray|Preserve|Private|Property|Protected|Public|RaiseEvent|ReadOnly|ReDim|RemoveHandler|Resume|Return|Select|Set|Shadows|Shared|Short|Single|Static|Step|Stop|String|Structure|Sub|SyncLock|Then|Throw|To|Try|TypeOf|Unicode|Until|Variant|Wend|When|While|With|WithEvents|WriteOnly|Xor|EndIf|GoSub|Let|Variant|Wend)\b/i,
null],[PR.PR_COMMENT,/^REM[^\r\n\u2028\u2029]*/i],[PR.PR_LITERAL,/^(?:True\b|False\b|Nothing\b|\d+(?:E[+\-]?\d+[FRD]?|[FRDSIL])?|(?:&H[0-9A-F]+|&O[0-7]+)[SIL]?|\d*\.\d+(?:E[+\-]?\d+)?[FRD]?|#\s+(?:\d+[\-\/]\d+[\-\/]\d+(?:\s+\d+:\d+(?::\d+)?(\s*(?:AM|PM))?)?|\d+:\d+(?::\d+)?(\s*(?:AM|PM))?)\s+#)/i],[PR.PR_PLAIN,/^(?:(?:[a-z]|_\w)\w*|\[(?:[a-z]|_\w)\w*\])/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r "'\[\]\xA0\u2018\u2019\u201C\u201D\u2028\u2029]+/],[PR.PR_PUNCTUATION,/^(?:\[|\])/]]),["vb","vbs"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"]],[[PR.PR_STRING,/^(?:[BOX]?"(?:[^"]|"")*"|'.')/i],[PR.PR_COMMENT,/^--[^\r\n]*/],[PR.PR_KEYWORD,/^(?:abs|access|after|alias|all|and|architecture|array|assert|attribute|begin|block|body|buffer|bus|case|component|configuration|constant|disconnect|downto|else|elsif|end|entity|exit|file|for|function|generate|generic|group|guarded|if|impure|in|inertial|inout|is|label|library|linkage|literal|loop|map|mod|nand|new|next|nor|not|null|of|on|open|or|others|out|package|port|postponed|procedure|process|pure|range|record|register|reject|rem|report|return|rol|ror|select|severity|shared|signal|sla|sll|sra|srl|subtype|then|to|transport|type|unaffected|units|until|use|variable|wait|when|while|with|xnor|xor)(?=[^\w-]|$)/i,
null],[PR.PR_TYPE,/^(?:bit|bit_vector|character|boolean|integer|real|time|string|severity_level|positive|natural|signed|unsigned|line|text|std_u?logic(?:_vector)?)(?=[^\w-]|$)/i,null],[PR.PR_TYPE,/^'(?:ACTIVE|ASCENDING|BASE|DELAYED|DRIVING|DRIVING_VALUE|EVENT|HIGH|IMAGE|INSTANCE_NAME|LAST_ACTIVE|LAST_EVENT|LAST_VALUE|LEFT|LEFTOF|LENGTH|LOW|PATH_NAME|POS|PRED|QUIET|RANGE|REVERSE_RANGE|RIGHT|RIGHTOF|SIMPLE_NAME|STABLE|SUCC|TRANSACTION|VAL|VALUE)(?=[^\w-]|$)/i,null],[PR.PR_LITERAL,/^\d+(?:_\d+)*(?:#[\w\\.]+#(?:[+\-]?\d+(?:_\d+)*)?|(?:\.\d+(?:_\d+)*)?(?:E[+\-]?\d+(?:_\d+)*)?)/i],
[PR.PR_PLAIN,/^(?:[a-z]\w*|\\[^\\]*\\)/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0"'][^\w\t\n\r \xA0\-"']*/]]),["vhdl","vhd"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t \xA0a-gi-z0-9]+/,null,"\t \u00a0abcdefgijklmnopqrstuvwxyz0123456789"],[PR.PR_PUNCTUATION,/^[=*~\^\[\]]+/,null,"=*~^[]"]],[["lang-wiki.meta",/(?:^^|\r\n?|\n)(#[a-z]+)\b/],[PR.PR_LITERAL,/^(?:[A-Z][a-z][a-z0-9]+[A-Z][a-z][a-zA-Z0-9]+)\b/],["lang-",/^\{\{\{([\s\S]+?)\}\}\}/],["lang-",/^`([^\r\n`]+)`/],[PR.PR_STRING,/^https?:\/\/[^\/?#\s]*(?:\/[^?#\s]*)?(?:\?[^#\s]*)?(?:#\S*)?/i],[PR.PR_PLAIN,/^(?:\r\n|[\s\S])[^#=*~^A-Zh\{`\[\r\n]*/]]),["wiki"]);
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_KEYWORD,/^#[a-z]+/i,null,"#"]],[]),["wiki.meta"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PUNCTUATION,/^[:|>?]+/,null,":|>?"],[PR.PR_DECLARATION,/^%(?:YAML|TAG)[^#\r\n]+/,null,"%"],[PR.PR_TYPE,/^[&]\S+/,null,"&"],[PR.PR_TYPE,/^!\S*/,null,"!"],[PR.PR_STRING,/^"(?:[^\\"]|\\.)*(?:"|$)/,null,'"'],[PR.PR_STRING,/^'(?:[^']|'')*(?:'|$)/,null,"'"],[PR.PR_COMMENT,/^#[^\r\n]*/,null,"#"],[PR.PR_PLAIN,/^\s+/,null," \t\r\n"]],[[PR.PR_DECLARATION,/^(?:---|\.\.\.)(?:[\r\n]|$)/],[PR.PR_PUNCTUATION,/^-/],[PR.PR_KEYWORD,/^\w+:[ \r\n]/],[PR.PR_PLAIN,/^\w+/]]),
["yaml","yml"]);_ds.w(cQ,_ds.R);cQ.prototype.whenReady=function(){return this.N.promise};
cQ.prototype.connectedCallback=function(){var a=this,b;return _ds.bb(function(c){switch(c.h){case 1:return _ds.y(c,DevsiteApp.whenReady(),2);case 2:return a.L||(eQ(a),dQ(a),a.L=!0),a.J.get("pref_dark-code")&&a.setAttribute("dark-code",""),a.N.resolve(),_ds.A(c,3),_ds.y(c,DevsiteApp.intersectionEnterForElement(a),5);case 5:_ds.B(c,4);break;case 3:if(b=_ds.C(c),"IntersectionObserver not supported"!==b.message)return c.return();case 4:var d=a.querySelector(".devsite-code-buttons-container");if(d)a.j=
d;else{a.j=_ds.vl(YP);a.hasAttribute("scope")&&(a.C=_ds.vl(bQ,{label:"JSFiddle\uc5d0\uc11c \ucf54\ub4dc \uc0d8\ud50c \uc5f4\uae30"}),(a.hasAttribute("jsfiddle-label")||a.hasAttribute("jsfiddle-title"))&&a.C.setAttribute("data-label",a.getAttribute("jsfiddle-label")||a.getAttribute("jsfiddle-title")),a.j.appendChild(a.C));a.D=_ds.vl(ZP,{label:"\uc5b4\ub450\uc6b4 \ucf54\ub4dc \ud14c\ub9c8"});a.j.appendChild(a.D);a.F=_ds.vl($P,{label:"\ubc1d\uc740 \ucf54\ub4dc \ud14c\ub9c8"});a.j.appendChild(a.F);if(!a.hasAttribute("no-copy")){d=
a.getAttribute("data-copy-event-label");var e="Click To Copy";d&&(e+=": "+d);a.o=_ds.vl(aQ,{label:a.K,np:e});a.j.appendChild(a.o)}a.prepend(a.j)}gQ(a);a.G=document.querySelector("devsite-snackbar");_ds.z(c)}})};cQ.prototype.disconnectedCallback=function(){var a=this;return _ds.bb(function(b){if(1==b.h)return _ds.y(b,DevsiteApp.whenReady(),2);DevsiteApp.unregisterIntersectionForElement(a);a.j&&a.removeChild(a.j);_ds.Ml(a.m);_ds.z(b)})};
cQ.prototype.attributeChangedCallback=function(a,b,c){var d=this;return _ds.bb(function(e){if(1==e.h){if("dark-code"!==a||b===c)return e.H(0);if(d.hasAttribute("dark-code"))return d.J.set("pref_dark-code","1"),_ds.y(e,_ds.Em(),6);d.J.remove("pref_dark-code");return _ds.y(e,_ds.Em(),5)}if(6!=e.h)return Array.from(document.querySelectorAll("devsite-code[dark-code]")).forEach(function(g){g.removeAttribute("dark-code")}),e.H(0);Array.from(document.querySelectorAll("devsite-code:not([dark-code])")).filter(function(g){return g!==
d}).forEach(function(g){g.setAttribute("dark-code","")});_ds.z(e)})};_ds.n.Object.defineProperties(cQ,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["dark-code"]}}});cQ.prototype.attributeChangedCallback=cQ.prototype.attributeChangedCallback;cQ.prototype.disconnectedCallback=cQ.prototype.disconnectedCallback;cQ.prototype.connectedCallback=cQ.prototype.connectedCallback;cQ.prototype.whenReady=cQ.prototype.whenReady;try{window.customElements.define("devsite-code",cQ)}catch(a){console.warn("devsite.app.customElement.DevsiteCode",a)};})(_ds_www);
