(function(_ds){var window=this;'use strict';var s3=function(a){var b=a.Qs,c=a.Tb,d=a.lp;a=a.Lq;var e='<ul class="devsite-nav-list"><li class="devsite-nav-item devsite-nav-heading devsite-toc-toggle" role="heading" aria-level="2"><span class="devsite-nav-title"><span class="devsite-nav-text">\ubaa9\ucc28</span></span>';c&&(e=e+'<button type="button" title="'+_ds.wj("\ucf58\ud150\uce20 \ud3bc\uce58\uae30/\uc811\uae30"),e+='" class="devsite-nav-show-all button-transparent material-icons"></button>');e+="</li>";for(var g=b.length,
h=0;h<g;h++){var k=b[h];e+='<li class="devsite-nav-item"'+(c&&k.index<a?" visible":"")+'><a href="#'+_ds.X(k.id)+'" class="devsite-nav-title gc-analytics-event" data-category="Site-Wide Custom Events" data-action="click" data-label="'+(c?"Embedded nav":"Right nav")+'" data-value="'+_ds.X(h)+'" track-type="navigation" track-name="'+(c?"embeddedNav":"rightNav")+'" track-metadata-position="'+_ds.X(h)+'" track-metadata-link-destination="#'+_ds.X(k.id)+'"><span class="devsite-nav-text" tooltip>'+_ds.U(k.text)+
"</span></a>";if(_ds.qj(k.children).length){e+='<ul class="devsite-nav-list">';k=k.children;for(var l=k.length,m=0;m<l;m++){var p=k[m];e+='<li class="devsite-nav-item"'+(c&&p.index<a?" visible":"")+'><a href="#'+_ds.X(p.id)+'" class="devsite-nav-title gc-analytics-event" data-category="Site-Wide Custom Events" data-action="click" data-label="'+(c?"Embedded nav":"Right nav")+'" data-value="'+_ds.X(h)+"."+_ds.X(m)+'" track-type="navigation" track-name="'+(c?"embeddedNav":"rightNav")+'" track-metadata-position="'+
_ds.X(h)+"."+_ds.X(m)+'" track-metadata-link-destination="#'+_ds.X(p.id)+'"><span class="devsite-nav-text" tooltip>'+_ds.U(p.text)+"</span></a></li>"}e+="</ul>"}e+="</li>"}d&&(e=c?e+'<li class="devsite-nav-item devsite-apix-link"><a href="#try-it" class="devsite-nav-title"><span class="devsite-nav-text" tooltip>\uc0ac\uc6a9\ud574 \ubcf4\uae30</span></a></li>':e+'<button type="button" class="devsite-show-apix button-primary">\uc0ac\uc6a9\ud574 \ubcf4\uae30</button>');c&&(e=e+'<li class="devsite-toc-toggle"><button type="button" class="button-flat devsite-nav-more-items material-icons" track-type="navigation" track-name="embeddedNavExpand" title="'+
_ds.wj("\ucf58\ud150\uce20 \ud3bc\uce58\uae30/\uc811\uae30"),e+='"></button></li>');return(0,_ds.T)(e+"</ul>")},B3=function(){var a=_ds.R.call(this)||this;a.eventHandler=new _ds.Gl;a.K=new _ds.On;a.D=new Set;a.F=new Map;a.N=new _ds.Ln(function(){return void t3(a)},16);a.L=new _ds.Ln(function(){return void u3(a)},33);a.o=null;a.m=null;a.j=[];a.G=!1;a.C=null;a.Tb=!1;a.J=[];a.O(_ds.Jh(v3),_ds.Jh(w3),_ds.Jh(x3),_ds.Jh(y3),_ds.Jh(z3),_ds.Jh(A3));return a},C3=function(a){a.Tb||a.eventHandler.listen(document.body,
"devsite-content-updated devsite-element-hidden devsite-element-visible devsite-page-loaded devsite-sticky-resize devsite-sticky-scroll".split(" "),function(){a.L.Aa()});a.eventHandler.listen(document.body,"devsite-content-updated",function(){t3(a)})},D3=function(a){_ds.Q(a,function c(){var d=this,e,g,h,k;return _ds.D(c,function(l){switch(l.h){case 1:e=d;if(!("IntersectionObserver"in _ds.zk())){l.H(2);break}d.C&&d.C.disconnect();g=document.querySelector("devsite-header");h=152;if(!g){l.H(3);break}return _ds.y(l,
window.customElements.whenDefined("devsite-header"),4);case 4:(k=Number(g.getAttribute("top-row--height"))+Number(g.getAttribute("bottom-row--height")))&&(h=k);case 3:d.C=new IntersectionObserver(function(m){m=_ds.r(m);for(var p=m.next();!p.done;p=m.next())p=p.value,p.isIntersecting?e.D.add(p.target):e.D.delete(p.target);e.L.Aa()},{rootMargin:h+"px 0px 0px 0px",threshold:[0,1]});case 2:d.K.resolve(),_ds.z(l)}})})},u3=function(a){return _ds.Q(a,function c(){var d=this;return _ds.D(c,function(e){if(1==
e.h)return _ds.y(e,E3(d),2);if(d.m){var g="#"+d.m.id,h=encodeURI(g);g=d.F.get(g)||d.F.get(h);d.o!==g&&(d.o&&d.o.classList.remove("devsite-nav-active"),g&&(g.classList.add("devsite-nav-active"),d.o=g))}_ds.z(e)})})},t3=function(a){if(!a.hasAttribute("disabled")){var b=document.querySelector("devsite-content .devsite-article-body");b?(a.Tb?a.classList.add("devsite-toc-embedded"):a.classList.add("devsite-toc"),F3(a,b),a.G=!0):a.eb()}},F3=function(a,b){var c=[],d=!1,e="";switch(a.getAttribute("depth")){case "1":e=
"h2:not(.hide-from-toc):not(#contents):not(#table-of-contents)";break;default:e="h2:not(.hide-from-toc):not(#contents):not(#table-of-contents), h3:not(.hide-from-toc):not(#contents):not(#table-of-contents)"}a.j=[].concat(_ds.ya(b.querySelectorAll(e))).filter(function(h){return h.id&&h.dataset.text}).filter(function(h){return G3(h)});b=_ds.r(a.j.entries());for(e=b.next();!e.done;e=b.next()){var g=_ds.r(e.value);e=g.next().value;g=g.next().value;e={id:g.id,level:g.tagName.toLowerCase(),text:g.dataset.text,
children:[],index:e};"h2"===e.level?(c.push(e),d=!0):d?c[c.length-1].children.push(e):c.push(e)}_ds.Tb(a.J,c,a.Bk.bind(a))&&a.G||(c.length?(H3(a,c),a.show(),a.Tb||I3(a)):a.eb(),a.J=c)},E3=function(a){return _ds.Q(a,function c(){var d=this,e,g,h,k,l,m,p,q;return _ds.D(c,function(t){switch(t.h){case 1:e=d;g=0;h=document.querySelector("devsite-header");if(!h){t.H(2);break}return _ds.y(t,window.customElements.whenDefined("devsite-header"),3);case 3:g=h.Kh();case 2:k=d.j.findIndex(function(u){return e.D.has(u)&&
u.getBoundingClientRect().top>=g});l=d.j[k];if(!l){d.m&&d.m.getBoundingClientRect().top>window.innerHeight&&(m=d.j.indexOf(d.m),0<m&&(d.m=d.j[m-1]));t.H(0);break}return _ds.y(t,J3(d),5);case 5:p=t.j,q=l.getBoundingClientRect().top-g,d.m=q>p&&0<k?d.j[k-1]:l,_ds.z(t)}})})},J3=function(a){return _ds.Q(a,function c(){var d,e,g,h;return _ds.D(c,function(k){if(1==k.h)return e=d=0,(g=document.querySelector("devsite-header"))?_ds.y(k,window.customElements.whenDefined("devsite-header"),3):k.H(2);2!=k.h&&(d=
g.Kh(),e=g.Wp());h=window.innerHeight-d;return k.return(Math.max(e-d,Math.floor(h/5)))})})},I3=function(a){_ds.Q(a,function c(){var d=this,e,g,h;return _ds.D(c,function(k){if(1==k.h)return _ds.y(k,d.K.promise,2);if(!d.C)return k.return();d.C.disconnect();d.D.clear();d.o&&d.o.classList.remove("devsite-nav-active");d.o=null;e=_ds.r(d.j);for(g=e.next();!g.done;g=e.next())h=g.value,d.C.observe(h);_ds.z(k)})})},G3=function(a){return _ds.kK.find(function(b){return!!_ds.nl(a,b,6)})||_ds.ml(a,"devsite-selector",
null,6)||_ds.nl(a,"devsite-dialog",3)?!1:!0},H3=function(a,b){var c=_ds.vl(s3,{Qs:b,Tb:a.Tb,lp:!!document.body.querySelector("devsite-apix, .devsite-apix"),Lq:5});b=_ds.r(c.querySelectorAll("a.devsite-nav-title"));for(var d=b.next();!d.done;d=b.next()){d=d.value;var e=d.hash,g=encodeURI(d.hash);a.F.set(e,d);a.F.set(g,d)}_ds.Gk(a);a.Tb&&_ds.ai(a,"hidden","",c);a.appendChild(c);if(a.Tb){if(8<=a.getElementsByClassName("devsite-nav-item").length){b=_ds.r(a.querySelectorAll(".devsite-nav-show-all, .devsite-nav-more-items"));
for(d=b.next();!d.done;d=b.next())a.eventHandler.listen(d.value,"click",function(){a.hasAttribute("expanded")?a.removeAttribute("expanded"):_ds.ai(a,"expanded","")});_ds.ai(a,"expandable","")}setTimeout(function(){c.removeAttribute("hidden")},0)}};var v3=_ds.xa(["disabled"]),w3=_ds.xa(["has-toc"]),x3=_ds.xa(["hidden"]),y3=_ds.xa(["expandable"]),z3=_ds.xa(["expanded"]),A3=_ds.xa(["visible"]);_ds.w(B3,_ds.R);_ds.f=B3.prototype;_ds.f.connectedCallback=function(){this.Tb=this.hasAttribute("devsite-toc-embedded");t3(this);C3(this)};_ds.f.disconnectedCallback=function(){this.eb();this.G=!1;_ds.Ml(this.eventHandler)};
_ds.f.Li=function(a){a=a&&"false"===a.toLowerCase();this.J=[];_ds.Gk(this);a?(_ds.ai(this,"disabled",""),this.eb()):(this.removeAttribute("disabled"),this.show(),this.N.Aa())};_ds.f.eb=function(){_ds.Gk(this);this.dispatchEvent(new CustomEvent("devsite-element-hidden",{bubbles:!0}));this.removeAttribute("visible");_ds.ai(this,"hidden","");if(!this.Tb){var a=document.querySelector(".devsite-main-content");a&&a.removeAttribute("has-toc")}};
_ds.f.show=function(){this.dispatchEvent(new CustomEvent("devsite-element-visible",{bubbles:!0}));this.removeAttribute("hidden");_ds.ai(this,"visible","");if(!this.Tb){var a=document.querySelector(".devsite-main-content");a&&_ds.ai(this,"has-toc","",a);D3(this)}};_ds.f.Bk=function(a,b){var c=!0;if(a.children.length||b.children.length)c=_ds.Tb(a.children,b.children,this.Bk.bind(this));return c&&a.id===b.id&&a.text===b.text};
_ds.n.Object.defineProperties(B3,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["max-height","offset"]}}});B3.prototype.renderUpdatedContent=B3.prototype.Li;B3.prototype.disconnectedCallback=B3.prototype.disconnectedCallback;B3.prototype.connectedCallback=B3.prototype.connectedCallback;try{window.customElements.define("devsite-toc",B3)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteToc",a)};})(_ds_www);
