(function(_ds){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var vT=function(a,b){sT()&&(b=tT()?"translate3d("+b+"px,0px,0px)":"translate("+b+"px,0px)",_ds.Rn(a,uT(),b))},yT=function(){var a=_ds.R.call(this)||this;a.N=-1;a.o=new _ds.Gl;a.J=new _ds.Gl;a.F=0;a.K=new MutationObserver(function(){return wT(a)});a.V=new _ds.Ln(function(){wT(a);xT(a)},15);a.C=0;a.j=0;a.D=0;a.m=0;a.G=!1;return a},AT=function(a){a.o.listen(a,"devsite-search-toggle",function(b){b=b.ma;_ds.nl(b.target,"devsite-top-logo-row-middle")&&(b.detail.active?a.setAttribute("search-active",
""):a.removeAttribute("search-active"))});a.o.listen(document.body,"devsite-sitemask-hidden",function(){return document.body.removeAttribute("devsite-book-nav--open")});a.o.listen(window,"resize",function(){return zT(a)});a.o.listen(document.body,["devsite-page-loaded","devsite-content-updated"],function(){zT(a)});a.o.listen(a,"click",function(b){b.defaultPrevented||"devsite-hamburger-menu"!=b.target.getAttribute("id")||(b.preventDefault(),b.stopPropagation(),document.body.setAttribute("devsite-book-nav--open",
""),a.dispatchEvent(new CustomEvent("devsite-sitemask-show",{bubbles:!0})))})},zT=function(a){window.requestAnimationFrame(function(){return a.V.Aa()})},BT=function(a,b){return(a=a.querySelector(b))?a.getBoundingClientRect().height:0},wT=function(a){a.C=BT(a,".devsite-top-logo-row-wrapper-wrapper");a.j=BT(a,".devsite-collapsible-section");a.D=BT(a,".devsite-doc-set-nav-row");a.setAttribute("top-row--height",a.C);a.setAttribute("bottom-row--height",a.j);a.setAttribute("bottom-tabs--height",a.D);document.body.style.setProperty("--devsite-js-header-top-row-height",
a.C+"px");document.body.style.setProperty("--devsite-js-header-lower-section-height",a.j+"px");document.body.style.setProperty("--devsite-js-header-lower-tabs-height",a.D+"px");document.body.style.setProperty("--devsite-js-header-height",a.Kh()+"px");CT(a)},DT=function(a){if(!a.querySelector(".devsite-search-background")&&(a=a.querySelector(".devsite-top-logo-row-middle"))){var b=document.createElement("div");b.classList.add("devsite-search-background");b.style.opacity=1;a.appendChild(b)}},CT=function(a){var b=
a.querySelector(".devsite-collapsible-section");a.m>=a.j&&!a.hasAttribute("bottom-row--hidden")?a.setAttribute("bottom-row--hidden",""):a.m<a.j-a.D&&a.hasAttribute("bottom-row--hidden")&&a.removeAttribute("bottom-row--hidden");b&&a.m!==a.N&&(document.body.style.setProperty("--devsite-js-header-lower-tabs-offset",a.m+"px"),_ds.Rn(b,"transform","translate3d(0, -"+a.m+"px, 0)"),xT(a),a.N=a.m)},ET=function(a){var b=a.querySelector(".devsite-top-logo-row-middle"),c=a.querySelector("devsite-search"),d=
a.querySelector(".devsite-search-background");if(b&&c&&d){_ds.Ml(a.J);a.F&&window.cancelAnimationFrame(a.F);c.removeAttribute("transition");a.removeAttribute("search-expanded");var e=new _ds.fk(b.offsetWidth,b.offsetHeight);b=new _ds.fk(c.offsetWidth,c.offsetHeight);var g=_ds.io(c,"margin"),h="rtl"===document.documentElement.getAttribute("dir")?1:-1,k=(e.width-g.left-g.right)/b.width;e=(e.width-(b.width+g.left+g.right))*h;var l=(g=a.hasAttribute("search-active"))?e:0,m=g?k:1;_ds.Rn(d,{opacity:1,width:b.width+
"px",height:b.height+"px"});vT(c,a.hasAttribute("search-active")?0:e);_ds.Kl(a.J,d,_ds.cm,function(){var p=a.querySelector("devsite-search"),q=a.querySelector(".devsite-search-background");q&&(q.style.opacity=0);p&&(p.removeAttribute("transition"),vT(p,0),a.hasAttribute("search-active")?a.setAttribute("search-expanded",""):a.removeAttribute("search-expanded"))});a.F=window.requestAnimationFrame(function(){c.setAttribute("transition","");if(sT()){var p=tT()?"scale3d("+m+",1,1)":"scale("+m+",1)";_ds.Rn(d,
uT(),p)}vT(c,l)})}},FT=function(a,b){var c,d,e,g;_ds.bb(function(h){if(1==h.h){if(!a.hasAttribute("billboard"))return h.return();c=a.querySelector("devsite-search");d=a.querySelector("devsite-search input.devsite-search-query");e=a.querySelector(".devsite-header-billboard-search devsite-search");g=e.querySelector("input.devsite-search-query");if(!b)return e.removeAttribute("disabled"),document.activeElement===d&&g.focus(),c.setAttribute("disabled",""),h.H(0);c.removeAttribute("disabled");return document.activeElement!==
g?h.H(3):_ds.y(h,_ds.Em(),4)}3!=h.h&&d.focus();e.setAttribute("disabled","");_ds.z(h)})},xT=function(a){0===a.j?a.setAttribute("no-lower-row",""):a.removeAttribute("no-lower-row");a.querySelector(".devsite-header-billboard")?a.setAttribute("billboard",""):a.removeAttribute("billboard")},GT=function(a,b){for(var c=0;c<b.attributes.length;++c){var d=b.attributes.item(c);a.hasAttribute(d.name)||b.removeAttribute(d.name)}for(c=0;c<a.attributes.length;++c)d=a.attributes.item(c),b.setAttribute(d.name,d.value)},
HT=function(a,b,c){b=b.querySelector(c);c=a.querySelector(c);b&&c&&(a.G=!0,_ds.bi(a,c,b))};var sT=_ds.Hb(function(){return!_ds.wk||0<=_ds.Hc(_ds.zL,9)}),tT=_ds.Hb(function(){return _ds.yk||_ds.RB||_ds.Tn&&0<=_ds.Hc(_ds.zL,10)||_ds.wk&&0<=_ds.Hc(_ds.zL,10)}),uT=_ds.Hb(function(){return _ds.wk&&9==_ds.Zn?"-ms-transform":"transform"});_ds.w(yT,_ds.R);_ds.f=yT.prototype;_ds.f.attributeChangedCallback=function(a,b,c){switch(a){case "offset":this.m=parseFloat(this.getAttribute("offset"))||0;CT(this);break;case "search-active":ET(this);break;case "bottom-row--hidden":a=null!==c,b=this.querySelector("devsite-search input.devsite-search-query"),c=this.querySelector(".devsite-header-billboard-search devsite-search input.devsite-search-query"),b&&c&&(a?b.value=c.value:c.value=b.value),FT(this,a)}};
_ds.f.connectedCallback=function(){AT(this);DT(this);xT(this);wT(this);this.K.observe(this,{childList:!0,subtree:!0});CT(this);var a=_ds.lm();this.L=_ds.aj(_ds.cj(a.href),"authuser")};_ds.f.disconnectedCallback=function(){_ds.Ml(this.o);this.K.disconnect()};_ds.f.Kh=function(){return this.C+this.j-this.m};_ds.f.Wp=function(){return this.C+this.j};
_ds.f.Wa=function(a){this.G=!1;if(a){HT(this,a,".devsite-header-upper-tabs");HT(this,a,".devsite-collapsible-section");HT(this,a,".devsite-product-name-wrapper");HT(this,a,"devsite-language-selector");HT(this,a,"devsite-shell-activate-button");var b=a.querySelector("devsite-search"),c=this.querySelector("devsite-search");b&&c&&GT(b,c);c=a.querySelector("devsite-user");b=this.querySelector("devsite-user");c&&b&&(GT(c,b),c=_ds.lm(),c=_ds.aj(_ds.cj(c.href),"authuser"),c!==this.L&&(this.L=c,b.refresh()));
_ds.bi(this,this.querySelector("cloudx-additional-tabs"),a.querySelector("cloudx-additional-tabs"),this.querySelector(".devsite-top-logo-row-middle"));_ds.bi(this,this.querySelector(".devsite-header-link"),a.querySelector(".devsite-header-link"),this.querySelector("devsite-language-selector"))}!this.G&&a&&(_ds.Gk(this),this.appendChild(a));DT(this);zT(this)};_ds.n.Object.defineProperties(yT,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["offset","search-active","bottom-row--hidden"]}}});
yT.prototype.updateContent=yT.prototype.Wa;yT.prototype.disconnectedCallback=yT.prototype.disconnectedCallback;yT.prototype.connectedCallback=yT.prototype.connectedCallback;yT.prototype.attributeChangedCallback=yT.prototype.attributeChangedCallback;try{window.customElements.define("devsite-header",yT)}catch(a){console.warn("devsite.app.customElement.DevsiteHeader",a)};})(_ds_www);
