(function(_ds){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var bY=function(){var a=_ds.R.call(this)||this;a.m=new _ds.Ao;a.j=new _ds.Gl;$X().then(function(){aY(a)});return a},aY=function(a){var b;return _ds.bb(function(c){return(b=_ds.qK.get("django_language"))?_ds.y(c,a.m.set("language_preference",b),0):c.H(0)})},dY=function(a){_ds.Ml(a.j);var b=a.querySelector(".devsite-language-selector-select");b&&a.j.listen(b,"change",function(c){cY(a,c)})},cY=function(a,b){var c,d;_ds.bb(function(e){switch(e.h){case 1:return _ds.y(e,DevsiteApp.whenReady(),
2);case 2:return _ds.qK.remove("django_language"),c=b.target,_ds.qK.set("django_language",c.value,{Jb:15552E3,path:"/"}),d=document.documentElement.getAttribute("lang"),_ds.y(e,eY(a,d,c.value),3);case 3:return _ds.y(e,aY(a),4);case 4:var g=_ds.bp(_ds.bj(new _ds.Hi(_ds.zk().location.href),"hl").toString());_ds.zk().location.assign(_ds.Vh(g));_ds.z(e)}})},eY=function(a,b,c){var d,e;return _ds.bb(function(g){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",
label:"Language Selector",action:b+" to "+c},bubbles:!0}));d={name:"change",type:"languageSelector",metadata:{"selected-language":c,"original-language":b}};e={eventData:JSON.stringify(d)};a.dispatchEvent(new CustomEvent("devsite-analytics-observation-cloudtrack",{detail:e,bubbles:!0}));_ds.z(g)})},$X=function(){return _ds.bb(function(a){if(1==a.h)return _ds.qK.get("django_language")?a.H(0):_ds.y(a,DevsiteApp.whenReady(),3);_ds.qK.set("django_language",DevsiteApp.getLocale()||"en",{Jb:15552E3,path:"/"});
_ds.z(a)})};_ds.w(bY,_ds.R);bY.prototype.connectedCallback=function(){dY(this)};bY.prototype.disconnectedCallback=function(){_ds.Ml(this.j)};bY.prototype.Wa=function(a){a&&(_ds.bi(this,this.querySelector(".devsite-language-selector-menu"),a.querySelector(".devsite-language-selector-menu")),dY(this))};bY.prototype.updateContent=bY.prototype.Wa;bY.prototype.disconnectedCallback=bY.prototype.disconnectedCallback;bY.prototype.connectedCallback=bY.prototype.connectedCallback;try{window.customElements.define("devsite-language-selector",bY)}catch(a){console.warn("devsite.app.customElement.DevsiteLanguageSelector",a)};})(_ds_www);
